<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmupdate
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing AndAlso components IsNot Nothing Then
            components.Dispose()
        End If
        MyBase.Dispose(disposing)
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmupdate))
        Dim ToolbarButton1 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton2 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton3 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton4 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton5 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton6 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton7 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton8 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton9 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton10 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton11 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton12 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton13 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton14 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim DataGridViewCellStyle1 As System.Windows.Forms.DataGridViewCellStyle = New System.Windows.Forms.DataGridViewCellStyle()
        Dim DataGridViewCellStyle2 As System.Windows.Forms.DataGridViewCellStyle = New System.Windows.Forms.DataGridViewCellStyle()
        Dim DataGridViewCellStyle3 As System.Windows.Forms.DataGridViewCellStyle = New System.Windows.Forms.DataGridViewCellStyle()
        Dim DataGridViewCellStyle4 As System.Windows.Forms.DataGridViewCellStyle = New System.Windows.Forms.DataGridViewCellStyle()
        Me.ILabel2 = New iControl.iLabel()
        Me.ILabel1 = New iControl.iLabel()
        Me.IButton1 = New iControl.iButton()
        Me.IButton2 = New iControl.iButton()
        Me.IForm1 = New iControl.iForm()
        Me.dtg1 = New iControl.iDataGridView(Me.components)
        Me.Column1 = New System.Windows.Forms.DataGridViewTextBoxColumn()
        CType(Me.dtg1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'ILabel2
        '
        Me.ILabel2.Anchor = CType((System.Windows.Forms.AnchorStyles.Bottom Or System.Windows.Forms.AnchorStyles.Left), System.Windows.Forms.AnchorStyles)
        Me.ILabel2.AutoSizeStyle = iControl.iLabel.eAutoSizeStyle.OnlyWitdh
        Me.ILabel2.AutoValidate = System.Windows.Forms.AutoValidate.Disable
        Me.ILabel2.Background = Nothing
        Me.ILabel2.BackgroundImage = CType(resources.GetObject("ILabel2.BackgroundImage"), System.Drawing.Image)
        Me.ILabel2.BorderColor = System.Drawing.Color.DimGray
        Me.ILabel2.BorderSize = 0
        Me.ILabel2.BorderVisible = False
        Me.ILabel2.Dull = False
        Me.ILabel2.Font = New System.Drawing.Font("Arial", 12.0!, System.Drawing.FontStyle.Underline, System.Drawing.GraphicsUnit.Pixel)
        Me.ILabel2.ForeColor = System.Drawing.Color.DimGray
        Me.ILabel2.Image = Global.ifupdll.My.Resources.Resources.bottom
        Me.ILabel2.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.ILabel2.InternalBorderColor = System.Drawing.Color.White
        Me.ILabel2.InternalBorderSize = 0
        Me.ILabel2.LineAlignment = System.Drawing.StringAlignment.Center
        Me.ILabel2.Location = New System.Drawing.Point(50, 65)
        Me.ILabel2.Margin = New System.Windows.Forms.Padding(4)
        Me.ILabel2.Name = "ILabel2"
        Me.ILabel2.Size = New System.Drawing.Size(264, 22)
        Me.ILabel2.SuspundeLayout = False
        Me.ILabel2.TabIndex = 7
        Me.ILabel2.Text = "Show detail"
        Me.ILabel2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.ILabel2.TextAntiAlis = False
        Me.ILabel2.TextGlowEffetct = False
        Me.ILabel2.TextShadows = False
        Me.ILabel2.TextVertical = False
        Me.ILabel2.ToolTip = ""
        Me.ILabel2.WordWrap = False
        '
        'ILabel1
        '
        Me.ILabel1.AutoSizeStyle = iControl.iLabel.eAutoSizeStyle.OnlyWitdh
        Me.ILabel1.AutoValidate = System.Windows.Forms.AutoValidate.Disable
        Me.ILabel1.Background = Nothing
        Me.ILabel1.BackgroundImage = CType(resources.GetObject("ILabel1.BackgroundImage"), System.Drawing.Image)
        Me.ILabel1.BorderColor = System.Drawing.Color.DimGray
        Me.ILabel1.BorderSize = 0
        Me.ILabel1.BorderVisible = False
        Me.ILabel1.Dull = False
        Me.ILabel1.Font = New System.Drawing.Font("Arial", 12.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel)
        Me.ILabel1.ForeColor = System.Drawing.Color.DimGray
        Me.ILabel1.Image = Global.ifupdll.My.Resources.Resources.info32
        Me.ILabel1.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.ILabel1.InternalBorderColor = System.Drawing.Color.White
        Me.ILabel1.InternalBorderSize = 0
        Me.ILabel1.LineAlignment = System.Drawing.StringAlignment.Center
        Me.ILabel1.Location = New System.Drawing.Point(16, 37)
        Me.ILabel1.Margin = New System.Windows.Forms.Padding(4)
        Me.ILabel1.Name = "ILabel1"
        Me.ILabel1.Size = New System.Drawing.Size(320, 36)
        Me.ILabel1.SuspundeLayout = False
        Me.ILabel1.TabIndex = 6
        Me.ILabel1.Text = "There is a new version!! do you want upgrade?"
        Me.ILabel1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.ILabel1.TextAntiAlis = False
        Me.ILabel1.TextGlowEffetct = False
        Me.ILabel1.TextShadows = False
        Me.ILabel1.TextVertical = False
        Me.ILabel1.ToolTip = ""
        Me.ILabel1.WordWrap = False
        '
        'IButton1
        '
        Me.IButton1.Anchor = CType((System.Windows.Forms.AnchorStyles.Bottom Or System.Windows.Forms.AnchorStyles.Left), System.Windows.Forms.AnchorStyles)
        Me.IButton1.BackColor = System.Drawing.Color.White
        Me.IButton1.Background = Nothing
        Me.IButton1.BackgroundImage = CType(resources.GetObject("IButton1.BackgroundImage"), System.Drawing.Image)
        Me.IButton1.BorderColorDisabled = System.Drawing.Color.Gainsboro
        Me.IButton1.BorderColorEnalbed = System.Drawing.Color.DarkGray
        Me.IButton1.BorderSize = 1
        Me.IButton1.ColorDisabled = System.Drawing.Color.WhiteSmoke
        Me.IButton1.ColorLeave = System.Drawing.Color.FromArgb(CType(CType(253, Byte), Integer), CType(CType(253, Byte), Integer), CType(CType(253, Byte), Integer))
        Me.IButton1.ColorOver = System.Drawing.Color.FromArgb(CType(CType(235, Byte), Integer), CType(CType(235, Byte), Integer), CType(CType(235, Byte), Integer))
        Me.IButton1.Dull = True
        Me.IButton1.FlatStyle = False
        Me.IButton1.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel, CType(0, Byte))
        Me.IButton1.ForeColor = System.Drawing.Color.RoyalBlue
        Me.IButton1.Image = Nothing
        Me.IButton1.Location = New System.Drawing.Point(86, 96)
        Me.IButton1.Margin = New System.Windows.Forms.Padding(5)
        Me.IButton1.Name = "IButton1"
        Me.IButton1.Size = New System.Drawing.Size(75, 24)
        Me.IButton1.SuspundeLayout = False
        Me.IButton1.TabIndex = 3
        Me.IButton1.Text = "Yes"
        Me.IButton1.TextAntiAlis = False
        Me.IButton1.TextGlowEffetct = False
        Me.IButton1.TextShadows = False
        Me.IButton1.ToolTip = ""
        '
        'IButton2
        '
        Me.IButton2.Anchor = CType((System.Windows.Forms.AnchorStyles.Bottom Or System.Windows.Forms.AnchorStyles.Left), System.Windows.Forms.AnchorStyles)
        Me.IButton2.BackColor = System.Drawing.Color.White
        Me.IButton2.Background = Nothing
        Me.IButton2.BackgroundImage = CType(resources.GetObject("IButton2.BackgroundImage"), System.Drawing.Image)
        Me.IButton2.BorderColorDisabled = System.Drawing.Color.Gainsboro
        Me.IButton2.BorderColorEnalbed = System.Drawing.Color.DarkGray
        Me.IButton2.BorderSize = 1
        Me.IButton2.ColorDisabled = System.Drawing.Color.WhiteSmoke
        Me.IButton2.ColorLeave = System.Drawing.Color.FromArgb(CType(CType(253, Byte), Integer), CType(CType(253, Byte), Integer), CType(CType(253, Byte), Integer))
        Me.IButton2.ColorOver = System.Drawing.Color.FromArgb(CType(CType(235, Byte), Integer), CType(CType(235, Byte), Integer), CType(CType(235, Byte), Integer))
        Me.IButton2.Dull = True
        Me.IButton2.FlatStyle = False
        Me.IButton2.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel, CType(0, Byte))
        Me.IButton2.ForeColor = System.Drawing.Color.Red
        Me.IButton2.Image = Nothing
        Me.IButton2.Location = New System.Drawing.Point(176, 96)
        Me.IButton2.Margin = New System.Windows.Forms.Padding(5)
        Me.IButton2.Name = "IButton2"
        Me.IButton2.Size = New System.Drawing.Size(75, 24)
        Me.IButton2.SuspundeLayout = False
        Me.IButton2.TabIndex = 2
        Me.IButton2.Text = "No"
        Me.IButton2.TextAntiAlis = False
        Me.IButton2.TextGlowEffetct = False
        Me.IButton2.TextShadows = False
        Me.IButton2.ToolTip = ""
        '
        'IForm1
        '
        Me.IForm1.BackColor = System.Drawing.Color.White
        Me.IForm1.BH1 = 0
        Me.IForm1.BH2 = 0
        Me.IForm1.BH3 = 0
        Me.IForm1.BH4 = 0
        Me.IForm1.BH5 = 0
        Me.IForm1.BH6 = 0
        Me.IForm1.CloseButton = True
        Me.IForm1.ControlBox = False
        Me.IForm1.Dock = System.Windows.Forms.DockStyle.Fill
        Me.IForm1.FlatStyle = False
        Me.IForm1.FontTitleWindows = New System.Drawing.Font("Arial", 11.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel)
        Me.IForm1.ForeColorTitleWindows = System.Drawing.Color.White
        Me.IForm1.Icon = Nothing
        Me.IForm1.Location = New System.Drawing.Point(0, 0)
        Me.IForm1.LogoLeft = Nothing
        Me.IForm1.LogoRight = CType(resources.GetObject("IForm1.LogoRight"), System.Drawing.Image)
        Me.IForm1.Margin = New System.Windows.Forms.Padding(4)
        Me.IForm1.MaximizeButton = False
        Me.IForm1.MinimizeButton = False
        Me.IForm1.Movable = True
        Me.IForm1.Name = "IForm1"
        Me.IForm1.Rel = ""
        Me.IForm1.ResizeType = iControl.iForm.eResizeType.All
        Me.IForm1.ShowBottomBar1 = True
        Me.IForm1.ShowBottomBar2 = True
        Me.IForm1.ShowBottomBar3 = True
        Me.IForm1.ShowBottomBarSeparator1 = True
        Me.IForm1.ShowBottomBarSeparator2 = True
        Me.IForm1.ShowBottomBarSeparator3 = False
        Me.IForm1.ShowLogoLeft = True
        Me.IForm1.ShowLogoRight = False
        Me.IForm1.ShowSystemMenu = True
        Me.IForm1.ShowTopBar1 = True
        Me.IForm1.ShowTopBar2 = True
        Me.IForm1.ShowTopBar3 = True
        Me.IForm1.ShowTopBarSeparator1 = False
        Me.IForm1.ShowTopBarSeparator2 = True
        Me.IForm1.ShowTopBarSeparator3 = True
        Me.IForm1.Sizable = False
        Me.IForm1.Size = New System.Drawing.Size(344, 134)
        Me.IForm1.SuspundeLayout = False
        Me.IForm1.TabIndex = 0
        Me.IForm1.TH1 = 0
        Me.IForm1.TH2 = 1
        Me.IForm1.TH3 = 0
        Me.IForm1.TH4 = 0
        Me.IForm1.TH5 = 0
        Me.IForm1.TH6 = 0
        Me.IForm1.Theme = "Red"
        Me.IForm1.Title = "Form"
        Me.IForm1.TitleAlign = iControl.iForm.align.Left
        '
        '
        '
        Me.IForm1.WindowMenu.AutoSize = True
        Me.IForm1.WindowMenu.AutoSizeMaxWidth = -1.0!
        Me.IForm1.WindowMenu.AutoSizeMinWidth = -1.0!
        Me.IForm1.WindowMenu.BackColor = System.Drawing.Color.White
        Me.IForm1.WindowMenu.Background = Nothing
        Me.IForm1.WindowMenu.BackgroundImage = CType(resources.GetObject("resource.BackgroundImage"), System.Drawing.Image)
        Me.IForm1.WindowMenu.BorderColor = System.Drawing.Color.Gray
        Me.IForm1.WindowMenu.BorderColorDropDown = System.Drawing.Color.Gray
        ToolbarButton1.BackColor = System.Drawing.Color.Empty
        ToolbarButton1.BorderColor = System.Drawing.Color.Silver
        ToolbarButton1.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton1.BorderVisible = False
        ToolbarButton1.CheckStyle = iControl.ToolbarButton.eCheckStyle.Check
        ToolbarButton1.CloseDropDownMenuAfterCheckBoxClick = True
        ToolbarButton1.CloseDropDownMenuAfterSubItemsClick = True
        ToolbarButton1.DefaultFont = Nothing
        ToolbarButton1.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton1.DefaultRowItemHeight = 0
        ToolbarButton1.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton1.DefaultTitleFont = Nothing
        ToolbarButton1.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton1.DropDown = False
        ToolbarButton1.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton1.DropDownMenuColoumnsCount = 1
        ToolbarButton1.Enabled = True
        ToolbarButton1.EnabledFirstDisplaySubItemSelected = True
        ToolbarButton1.EnableSubItemsSelection = True
        ToolbarButton1.Font = Nothing
        ToolbarButton1.ForeColor = System.Drawing.Color.Empty
        ToolbarButton1.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton1.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton1.FullRowSelect = False
        ToolbarButton1.Image = Nothing
        ToolbarButton1.Index = 0
        ToolbarButton1.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton1.InternalBorderVisible = False
        ToolbarButton1.MaxDropDownItems = 0
        ToolbarButton1.MaxSubWidth = -1
        ToolbarButton1.MaxWidth = -1
        ToolbarButton1.MenuHorizontalAlignment = -1
        ToolbarButton1.MenuVerticalAlignment = -1
        ToolbarButton1.MinSubWidth = -1
        ToolbarButton1.MinWidth = -1
        ToolbarButton1.Name = ""
        ToolbarButton1.RowsHeightAutoSize = True
        ToolbarButton1.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton1.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton1.ShowColumnCheck = False
        ToolbarButton1.ShowColumnImage = False
        ToolbarButton1.State = False
        ToolbarButton1.SubButtonsContextMenuStrip = Nothing
        ToolbarButton1.SubColumnWidth = CType(resources.GetObject("ToolbarButton1.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton1.SubHeight = 100
        ToolbarButton1.SubItemsAutoSize = False
        ToolbarButton1.SubWidth = 100
        ToolbarButton1.Tag = Nothing
        ToolbarButton1.Text = "Menu"
        ToolbarButton1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton1.ToolTips = ""
        ToolbarButton1.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton1.Visible = True
        ToolbarButton1.Width = 47
        ToolbarButton2.BackColor = System.Drawing.Color.Empty
        ToolbarButton2.BorderColor = System.Drawing.Color.Silver
        ToolbarButton2.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton2.BorderVisible = False
        ToolbarButton2.CheckStyle = iControl.ToolbarButton.eCheckStyle.Check
        ToolbarButton2.CloseDropDownMenuAfterCheckBoxClick = True
        ToolbarButton2.CloseDropDownMenuAfterSubItemsClick = True
        ToolbarButton2.DefaultFont = Nothing
        ToolbarButton2.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton2.DefaultRowItemHeight = 0
        ToolbarButton2.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton2.DefaultTitleFont = Nothing
        ToolbarButton2.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton2.DropDown = False
        ToolbarButton2.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton2.DropDownMenuColoumnsCount = 1
        ToolbarButton2.Enabled = True
        ToolbarButton2.EnabledFirstDisplaySubItemSelected = True
        ToolbarButton2.EnableSubItemsSelection = True
        ToolbarButton2.Font = Nothing
        ToolbarButton2.ForeColor = System.Drawing.Color.Empty
        ToolbarButton2.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton2.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton2.FullRowSelect = False
        ToolbarButton2.Image = Nothing
        ToolbarButton2.Index = 1
        ToolbarButton2.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton2.InternalBorderVisible = False
        ToolbarButton2.MaxDropDownItems = 0
        ToolbarButton2.MaxSubWidth = -1
        ToolbarButton2.MaxWidth = -1
        ToolbarButton2.MenuHorizontalAlignment = -1
        ToolbarButton2.MenuVerticalAlignment = -1
        ToolbarButton2.MinSubWidth = -1
        ToolbarButton2.MinWidth = -1
        ToolbarButton2.Name = ""
        ToolbarButton2.RowsHeightAutoSize = True
        ToolbarButton2.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton2.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton2.ShowColumnCheck = False
        ToolbarButton2.ShowColumnImage = False
        ToolbarButton2.State = False
        ToolbarButton2.SubButtonsContextMenuStrip = Nothing
        ToolbarButton2.SubColumnWidth = CType(resources.GetObject("ToolbarButton2.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton2.SubHeight = 100
        ToolbarButton2.SubItemsAutoSize = False
        ToolbarButton2.SubWidth = 100
        ToolbarButton2.Tag = Nothing
        ToolbarButton2.Text = "Menu"
        ToolbarButton2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton2.ToolTips = ""
        ToolbarButton2.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton2.Visible = True
        ToolbarButton2.Width = 47
        ToolbarButton3.BackColor = System.Drawing.Color.Empty
        ToolbarButton3.BorderColor = System.Drawing.Color.Silver
        ToolbarButton3.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton3.BorderVisible = False
        ToolbarButton3.CheckStyle = iControl.ToolbarButton.eCheckStyle.Check
        ToolbarButton3.CloseDropDownMenuAfterCheckBoxClick = True
        ToolbarButton3.CloseDropDownMenuAfterSubItemsClick = True
        ToolbarButton3.DefaultFont = Nothing
        ToolbarButton3.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton3.DefaultRowItemHeight = 0
        ToolbarButton3.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton3.DefaultTitleFont = Nothing
        ToolbarButton3.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton3.DropDown = False
        ToolbarButton3.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton3.DropDownMenuColoumnsCount = 1
        ToolbarButton3.Enabled = True
        ToolbarButton3.EnabledFirstDisplaySubItemSelected = True
        ToolbarButton3.EnableSubItemsSelection = True
        ToolbarButton3.Font = Nothing
        ToolbarButton3.ForeColor = System.Drawing.Color.Empty
        ToolbarButton3.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton3.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton3.FullRowSelect = False
        ToolbarButton3.Image = Nothing
        ToolbarButton3.Index = 2
        ToolbarButton3.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton3.InternalBorderVisible = False
        ToolbarButton3.MaxDropDownItems = 0
        ToolbarButton3.MaxSubWidth = -1
        ToolbarButton3.MaxWidth = -1
        ToolbarButton3.MenuHorizontalAlignment = -1
        ToolbarButton3.MenuVerticalAlignment = -1
        ToolbarButton3.MinSubWidth = -1
        ToolbarButton3.MinWidth = -1
        ToolbarButton3.Name = ""
        ToolbarButton3.RowsHeightAutoSize = True
        ToolbarButton3.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton3.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton3.ShowColumnCheck = False
        ToolbarButton3.ShowColumnImage = False
        ToolbarButton3.State = False
        ToolbarButton3.SubButtonsContextMenuStrip = Nothing
        ToolbarButton3.SubColumnWidth = CType(resources.GetObject("ToolbarButton3.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton3.SubHeight = 100
        ToolbarButton3.SubItemsAutoSize = False
        ToolbarButton3.SubWidth = 100
        ToolbarButton3.Tag = Nothing
        ToolbarButton3.Text = "Menu"
        ToolbarButton3.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton3.ToolTips = ""
        ToolbarButton3.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton3.Visible = True
        ToolbarButton3.Width = 47
        ToolbarButton4.BackColor = System.Drawing.Color.Empty
        ToolbarButton4.BorderColor = System.Drawing.Color.Silver
        ToolbarButton4.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton4.BorderVisible = False
        ToolbarButton4.CheckStyle = iControl.ToolbarButton.eCheckStyle.Check
        ToolbarButton4.CloseDropDownMenuAfterCheckBoxClick = True
        ToolbarButton4.CloseDropDownMenuAfterSubItemsClick = True
        ToolbarButton4.DefaultFont = Nothing
        ToolbarButton4.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton4.DefaultRowItemHeight = 0
        ToolbarButton4.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton4.DefaultTitleFont = Nothing
        ToolbarButton4.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton4.DropDown = False
        ToolbarButton4.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton4.DropDownMenuColoumnsCount = 1
        ToolbarButton4.Enabled = True
        ToolbarButton4.EnabledFirstDisplaySubItemSelected = True
        ToolbarButton4.EnableSubItemsSelection = True
        ToolbarButton4.Font = Nothing
        ToolbarButton4.ForeColor = System.Drawing.Color.Empty
        ToolbarButton4.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton4.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton4.FullRowSelect = False
        ToolbarButton4.Image = Nothing
        ToolbarButton4.Index = 3
        ToolbarButton4.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton4.InternalBorderVisible = False
        ToolbarButton4.MaxDropDownItems = 0
        ToolbarButton4.MaxSubWidth = -1
        ToolbarButton4.MaxWidth = -1
        ToolbarButton4.MenuHorizontalAlignment = -1
        ToolbarButton4.MenuVerticalAlignment = -1
        ToolbarButton4.MinSubWidth = -1
        ToolbarButton4.MinWidth = -1
        ToolbarButton4.Name = ""
        ToolbarButton4.RowsHeightAutoSize = True
        ToolbarButton4.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton4.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton4.ShowColumnCheck = False
        ToolbarButton4.ShowColumnImage = False
        ToolbarButton4.State = False
        ToolbarButton4.SubButtonsContextMenuStrip = Nothing
        ToolbarButton4.SubColumnWidth = CType(resources.GetObject("ToolbarButton4.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton4.SubHeight = 100
        ToolbarButton4.SubItemsAutoSize = False
        ToolbarButton4.SubWidth = 100
        ToolbarButton4.Tag = Nothing
        ToolbarButton4.Text = "Menu"
        ToolbarButton4.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton4.ToolTips = ""
        ToolbarButton4.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton4.Visible = True
        ToolbarButton4.Width = 47
        ToolbarButton5.BackColor = System.Drawing.Color.Empty
        ToolbarButton5.BorderColor = System.Drawing.Color.Silver
        ToolbarButton5.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton5.BorderVisible = False
        ToolbarButton5.CheckStyle = iControl.ToolbarButton.eCheckStyle.Check
        ToolbarButton5.CloseDropDownMenuAfterCheckBoxClick = True
        ToolbarButton5.CloseDropDownMenuAfterSubItemsClick = True
        ToolbarButton5.DefaultFont = Nothing
        ToolbarButton5.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton5.DefaultRowItemHeight = 0
        ToolbarButton5.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton5.DefaultTitleFont = Nothing
        ToolbarButton5.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton5.DropDown = False
        ToolbarButton5.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton5.DropDownMenuColoumnsCount = 1
        ToolbarButton5.Enabled = True
        ToolbarButton5.EnabledFirstDisplaySubItemSelected = True
        ToolbarButton5.EnableSubItemsSelection = True
        ToolbarButton5.Font = Nothing
        ToolbarButton5.ForeColor = System.Drawing.Color.Empty
        ToolbarButton5.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton5.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton5.FullRowSelect = False
        ToolbarButton5.Image = Nothing
        ToolbarButton5.Index = 4
        ToolbarButton5.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton5.InternalBorderVisible = False
        ToolbarButton5.MaxDropDownItems = 0
        ToolbarButton5.MaxSubWidth = -1
        ToolbarButton5.MaxWidth = -1
        ToolbarButton5.MenuHorizontalAlignment = -1
        ToolbarButton5.MenuVerticalAlignment = -1
        ToolbarButton5.MinSubWidth = -1
        ToolbarButton5.MinWidth = -1
        ToolbarButton5.Name = ""
        ToolbarButton5.RowsHeightAutoSize = True
        ToolbarButton5.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton5.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton5.ShowColumnCheck = False
        ToolbarButton5.ShowColumnImage = False
        ToolbarButton5.State = False
        ToolbarButton5.SubButtonsContextMenuStrip = Nothing
        ToolbarButton5.SubColumnWidth = CType(resources.GetObject("ToolbarButton5.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton5.SubHeight = 100
        ToolbarButton5.SubItemsAutoSize = False
        ToolbarButton5.SubWidth = 100
        ToolbarButton5.Tag = Nothing
        ToolbarButton5.Text = "Menu"
        ToolbarButton5.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton5.ToolTips = ""
        ToolbarButton5.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton5.Visible = True
        ToolbarButton5.Width = 47
        ToolbarButton6.BackColor = System.Drawing.Color.Empty
        ToolbarButton6.BorderColor = System.Drawing.Color.Silver
        ToolbarButton6.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton6.BorderVisible = False
        ToolbarButton6.CheckStyle = iControl.ToolbarButton.eCheckStyle.Check
        ToolbarButton6.CloseDropDownMenuAfterCheckBoxClick = True
        ToolbarButton6.CloseDropDownMenuAfterSubItemsClick = True
        ToolbarButton6.DefaultFont = Nothing
        ToolbarButton6.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton6.DefaultRowItemHeight = 0
        ToolbarButton6.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton6.DefaultTitleFont = Nothing
        ToolbarButton6.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton6.DropDown = False
        ToolbarButton6.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton6.DropDownMenuColoumnsCount = 1
        ToolbarButton6.Enabled = True
        ToolbarButton6.EnabledFirstDisplaySubItemSelected = True
        ToolbarButton6.EnableSubItemsSelection = True
        ToolbarButton6.Font = Nothing
        ToolbarButton6.ForeColor = System.Drawing.Color.Empty
        ToolbarButton6.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton6.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton6.FullRowSelect = False
        ToolbarButton6.Image = Nothing
        ToolbarButton6.Index = 5
        ToolbarButton6.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton6.InternalBorderVisible = False
        ToolbarButton6.MaxDropDownItems = 0
        ToolbarButton6.MaxSubWidth = -1
        ToolbarButton6.MaxWidth = -1
        ToolbarButton6.MenuHorizontalAlignment = -1
        ToolbarButton6.MenuVerticalAlignment = -1
        ToolbarButton6.MinSubWidth = -1
        ToolbarButton6.MinWidth = -1
        ToolbarButton6.Name = ""
        ToolbarButton6.RowsHeightAutoSize = True
        ToolbarButton6.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton6.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton6.ShowColumnCheck = False
        ToolbarButton6.ShowColumnImage = False
        ToolbarButton6.State = False
        ToolbarButton6.SubButtonsContextMenuStrip = Nothing
        ToolbarButton6.SubColumnWidth = CType(resources.GetObject("ToolbarButton6.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton6.SubHeight = 100
        ToolbarButton6.SubItemsAutoSize = False
        ToolbarButton6.SubWidth = 100
        ToolbarButton6.Tag = Nothing
        ToolbarButton6.Text = "Menu"
        ToolbarButton6.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton6.ToolTips = ""
        ToolbarButton6.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton6.Visible = True
        ToolbarButton6.Width = 47
        ToolbarButton7.BackColor = System.Drawing.Color.Empty
        ToolbarButton7.BorderColor = System.Drawing.Color.Silver
        ToolbarButton7.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton7.BorderVisible = False
        ToolbarButton7.CheckStyle = iControl.ToolbarButton.eCheckStyle.Check
        ToolbarButton7.CloseDropDownMenuAfterCheckBoxClick = True
        ToolbarButton7.CloseDropDownMenuAfterSubItemsClick = True
        ToolbarButton7.DefaultFont = Nothing
        ToolbarButton7.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton7.DefaultRowItemHeight = 0
        ToolbarButton7.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton7.DefaultTitleFont = Nothing
        ToolbarButton7.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton7.DropDown = False
        ToolbarButton7.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton7.DropDownMenuColoumnsCount = 1
        ToolbarButton7.Enabled = True
        ToolbarButton7.EnabledFirstDisplaySubItemSelected = True
        ToolbarButton7.EnableSubItemsSelection = True
        ToolbarButton7.Font = Nothing
        ToolbarButton7.ForeColor = System.Drawing.Color.Empty
        ToolbarButton7.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton7.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton7.FullRowSelect = False
        ToolbarButton7.Image = Nothing
        ToolbarButton7.Index = 6
        ToolbarButton7.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton7.InternalBorderVisible = False
        ToolbarButton7.MaxDropDownItems = 0
        ToolbarButton7.MaxSubWidth = -1
        ToolbarButton7.MaxWidth = -1
        ToolbarButton7.MenuHorizontalAlignment = -1
        ToolbarButton7.MenuVerticalAlignment = -1
        ToolbarButton7.MinSubWidth = -1
        ToolbarButton7.MinWidth = -1
        ToolbarButton7.Name = ""
        ToolbarButton7.RowsHeightAutoSize = True
        ToolbarButton7.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton7.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton7.ShowColumnCheck = False
        ToolbarButton7.ShowColumnImage = False
        ToolbarButton7.State = False
        ToolbarButton7.SubButtonsContextMenuStrip = Nothing
        ToolbarButton7.SubColumnWidth = CType(resources.GetObject("ToolbarButton7.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton7.SubHeight = 100
        ToolbarButton7.SubItemsAutoSize = False
        ToolbarButton7.SubWidth = 100
        ToolbarButton7.Tag = Nothing
        ToolbarButton7.Text = "Menu"
        ToolbarButton7.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton7.ToolTips = ""
        ToolbarButton7.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton7.Visible = True
        ToolbarButton7.Width = 47
        ToolbarButton8.BackColor = System.Drawing.Color.Empty
        ToolbarButton8.BorderColor = System.Drawing.Color.Silver
        ToolbarButton8.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton8.BorderVisible = False
        ToolbarButton8.CheckStyle = iControl.ToolbarButton.eCheckStyle.Check
        ToolbarButton8.CloseDropDownMenuAfterCheckBoxClick = True
        ToolbarButton8.CloseDropDownMenuAfterSubItemsClick = True
        ToolbarButton8.DefaultFont = Nothing
        ToolbarButton8.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton8.DefaultRowItemHeight = 0
        ToolbarButton8.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton8.DefaultTitleFont = Nothing
        ToolbarButton8.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton8.DropDown = False
        ToolbarButton8.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton8.DropDownMenuColoumnsCount = 1
        ToolbarButton8.Enabled = True
        ToolbarButton8.EnabledFirstDisplaySubItemSelected = True
        ToolbarButton8.EnableSubItemsSelection = True
        ToolbarButton8.Font = Nothing
        ToolbarButton8.ForeColor = System.Drawing.Color.Empty
        ToolbarButton8.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton8.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton8.FullRowSelect = False
        ToolbarButton8.Image = Nothing
        ToolbarButton8.Index = 7
        ToolbarButton8.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton8.InternalBorderVisible = False
        ToolbarButton8.MaxDropDownItems = 0
        ToolbarButton8.MaxSubWidth = -1
        ToolbarButton8.MaxWidth = -1
        ToolbarButton8.MenuHorizontalAlignment = -1
        ToolbarButton8.MenuVerticalAlignment = -1
        ToolbarButton8.MinSubWidth = -1
        ToolbarButton8.MinWidth = -1
        ToolbarButton8.Name = ""
        ToolbarButton8.RowsHeightAutoSize = True
        ToolbarButton8.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton8.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton8.ShowColumnCheck = False
        ToolbarButton8.ShowColumnImage = False
        ToolbarButton8.State = False
        ToolbarButton8.SubButtonsContextMenuStrip = Nothing
        ToolbarButton8.SubColumnWidth = Nothing
        ToolbarButton8.SubHeight = 100
        ToolbarButton8.SubItemsAutoSize = False
        ToolbarButton8.SubWidth = 100
        ToolbarButton8.Tag = Nothing
        ToolbarButton8.Text = "Menu"
        ToolbarButton8.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton8.ToolTips = ""
        ToolbarButton8.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton8.Visible = True
        ToolbarButton8.Width = 47
        ToolbarButton9.BackColor = System.Drawing.Color.Empty
        ToolbarButton9.BorderColor = System.Drawing.Color.Silver
        ToolbarButton9.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton9.BorderVisible = False
        ToolbarButton9.CheckStyle = iControl.ToolbarButton.eCheckStyle.Check
        ToolbarButton9.CloseDropDownMenuAfterCheckBoxClick = True
        ToolbarButton9.CloseDropDownMenuAfterSubItemsClick = True
        ToolbarButton9.DefaultFont = Nothing
        ToolbarButton9.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton9.DefaultRowItemHeight = 0
        ToolbarButton9.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton9.DefaultTitleFont = Nothing
        ToolbarButton9.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton9.DropDown = False
        ToolbarButton9.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton9.DropDownMenuColoumnsCount = 1
        ToolbarButton9.Enabled = True
        ToolbarButton9.EnabledFirstDisplaySubItemSelected = True
        ToolbarButton9.EnableSubItemsSelection = True
        ToolbarButton9.Font = Nothing
        ToolbarButton9.ForeColor = System.Drawing.Color.Empty
        ToolbarButton9.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton9.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton9.FullRowSelect = False
        ToolbarButton9.Image = Nothing
        ToolbarButton9.Index = 8
        ToolbarButton9.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton9.InternalBorderVisible = False
        ToolbarButton9.MaxDropDownItems = 0
        ToolbarButton9.MaxSubWidth = -1
        ToolbarButton9.MaxWidth = -1
        ToolbarButton9.MenuHorizontalAlignment = -1
        ToolbarButton9.MenuVerticalAlignment = -1
        ToolbarButton9.MinSubWidth = -1
        ToolbarButton9.MinWidth = -1
        ToolbarButton9.Name = ""
        ToolbarButton9.RowsHeightAutoSize = True
        ToolbarButton9.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton9.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton9.ShowColumnCheck = False
        ToolbarButton9.ShowColumnImage = False
        ToolbarButton9.State = False
        ToolbarButton9.SubButtonsContextMenuStrip = Nothing
        ToolbarButton9.SubColumnWidth = Nothing
        ToolbarButton9.SubHeight = 100
        ToolbarButton9.SubItemsAutoSize = False
        ToolbarButton9.SubWidth = 100
        ToolbarButton9.Tag = Nothing
        ToolbarButton9.Text = "Menu"
        ToolbarButton9.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton9.ToolTips = ""
        ToolbarButton9.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton9.Visible = True
        ToolbarButton9.Width = 47
        ToolbarButton10.BackColor = System.Drawing.Color.Empty
        ToolbarButton10.BorderColor = System.Drawing.Color.Silver
        ToolbarButton10.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton10.BorderVisible = False
        ToolbarButton10.CheckStyle = iControl.ToolbarButton.eCheckStyle.Check
        ToolbarButton10.CloseDropDownMenuAfterCheckBoxClick = True
        ToolbarButton10.CloseDropDownMenuAfterSubItemsClick = True
        ToolbarButton10.DefaultFont = Nothing
        ToolbarButton10.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton10.DefaultRowItemHeight = 0
        ToolbarButton10.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton10.DefaultTitleFont = Nothing
        ToolbarButton10.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton10.DropDown = False
        ToolbarButton10.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton10.DropDownMenuColoumnsCount = 1
        ToolbarButton10.Enabled = True
        ToolbarButton10.EnabledFirstDisplaySubItemSelected = True
        ToolbarButton10.EnableSubItemsSelection = True
        ToolbarButton10.Font = Nothing
        ToolbarButton10.ForeColor = System.Drawing.Color.Empty
        ToolbarButton10.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton10.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton10.FullRowSelect = False
        ToolbarButton10.Image = Nothing
        ToolbarButton10.Index = 9
        ToolbarButton10.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton10.InternalBorderVisible = False
        ToolbarButton10.MaxDropDownItems = 0
        ToolbarButton10.MaxSubWidth = -1
        ToolbarButton10.MaxWidth = -1
        ToolbarButton10.MenuHorizontalAlignment = -1
        ToolbarButton10.MenuVerticalAlignment = -1
        ToolbarButton10.MinSubWidth = -1
        ToolbarButton10.MinWidth = -1
        ToolbarButton10.Name = ""
        ToolbarButton10.RowsHeightAutoSize = True
        ToolbarButton10.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton10.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton10.ShowColumnCheck = False
        ToolbarButton10.ShowColumnImage = False
        ToolbarButton10.State = False
        ToolbarButton10.SubButtonsContextMenuStrip = Nothing
        ToolbarButton10.SubColumnWidth = Nothing
        ToolbarButton10.SubHeight = 100
        ToolbarButton10.SubItemsAutoSize = False
        ToolbarButton10.SubWidth = 100
        ToolbarButton10.Tag = Nothing
        ToolbarButton10.Text = "Menu"
        ToolbarButton10.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton10.ToolTips = ""
        ToolbarButton10.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton10.Visible = True
        ToolbarButton10.Width = 47
        ToolbarButton11.BackColor = System.Drawing.Color.Empty
        ToolbarButton11.BorderColor = System.Drawing.Color.Silver
        ToolbarButton11.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton11.BorderVisible = False
        ToolbarButton11.CheckStyle = iControl.ToolbarButton.eCheckStyle.Check
        ToolbarButton11.CloseDropDownMenuAfterCheckBoxClick = True
        ToolbarButton11.CloseDropDownMenuAfterSubItemsClick = True
        ToolbarButton11.DefaultFont = Nothing
        ToolbarButton11.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton11.DefaultRowItemHeight = 0
        ToolbarButton11.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton11.DefaultTitleFont = Nothing
        ToolbarButton11.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton11.DropDown = False
        ToolbarButton11.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton11.DropDownMenuColoumnsCount = 1
        ToolbarButton11.Enabled = True
        ToolbarButton11.EnabledFirstDisplaySubItemSelected = True
        ToolbarButton11.EnableSubItemsSelection = True
        ToolbarButton11.Font = Nothing
        ToolbarButton11.ForeColor = System.Drawing.Color.Empty
        ToolbarButton11.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton11.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton11.FullRowSelect = False
        ToolbarButton11.Image = Nothing
        ToolbarButton11.Index = 10
        ToolbarButton11.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton11.InternalBorderVisible = False
        ToolbarButton11.MaxDropDownItems = 0
        ToolbarButton11.MaxSubWidth = -1
        ToolbarButton11.MaxWidth = -1
        ToolbarButton11.MenuHorizontalAlignment = -1
        ToolbarButton11.MenuVerticalAlignment = -1
        ToolbarButton11.MinSubWidth = -1
        ToolbarButton11.MinWidth = -1
        ToolbarButton11.Name = ""
        ToolbarButton11.RowsHeightAutoSize = True
        ToolbarButton11.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton11.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton11.ShowColumnCheck = False
        ToolbarButton11.ShowColumnImage = False
        ToolbarButton11.State = False
        ToolbarButton11.SubButtonsContextMenuStrip = Nothing
        ToolbarButton11.SubColumnWidth = Nothing
        ToolbarButton11.SubHeight = 100
        ToolbarButton11.SubItemsAutoSize = False
        ToolbarButton11.SubWidth = 100
        ToolbarButton11.Tag = Nothing
        ToolbarButton11.Text = "Menu"
        ToolbarButton11.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton11.ToolTips = ""
        ToolbarButton11.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton11.Visible = True
        ToolbarButton11.Width = 47
        ToolbarButton12.BackColor = System.Drawing.Color.Empty
        ToolbarButton12.BorderColor = System.Drawing.Color.Silver
        ToolbarButton12.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton12.BorderVisible = False
        ToolbarButton12.CheckStyle = iControl.ToolbarButton.eCheckStyle.Check
        ToolbarButton12.CloseDropDownMenuAfterCheckBoxClick = True
        ToolbarButton12.CloseDropDownMenuAfterSubItemsClick = True
        ToolbarButton12.DefaultFont = Nothing
        ToolbarButton12.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton12.DefaultRowItemHeight = 0
        ToolbarButton12.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton12.DefaultTitleFont = Nothing
        ToolbarButton12.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton12.DropDown = False
        ToolbarButton12.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton12.DropDownMenuColoumnsCount = 1
        ToolbarButton12.Enabled = True
        ToolbarButton12.EnabledFirstDisplaySubItemSelected = True
        ToolbarButton12.EnableSubItemsSelection = True
        ToolbarButton12.Font = Nothing
        ToolbarButton12.ForeColor = System.Drawing.Color.Empty
        ToolbarButton12.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton12.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton12.FullRowSelect = False
        ToolbarButton12.Image = Nothing
        ToolbarButton12.Index = 11
        ToolbarButton12.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton12.InternalBorderVisible = False
        ToolbarButton12.MaxDropDownItems = 0
        ToolbarButton12.MaxSubWidth = -1
        ToolbarButton12.MaxWidth = -1
        ToolbarButton12.MenuHorizontalAlignment = -1
        ToolbarButton12.MenuVerticalAlignment = -1
        ToolbarButton12.MinSubWidth = -1
        ToolbarButton12.MinWidth = -1
        ToolbarButton12.Name = ""
        ToolbarButton12.RowsHeightAutoSize = True
        ToolbarButton12.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton12.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton12.ShowColumnCheck = False
        ToolbarButton12.ShowColumnImage = False
        ToolbarButton12.State = False
        ToolbarButton12.SubButtonsContextMenuStrip = Nothing
        ToolbarButton12.SubColumnWidth = Nothing
        ToolbarButton12.SubHeight = 100
        ToolbarButton12.SubItemsAutoSize = False
        ToolbarButton12.SubWidth = 100
        ToolbarButton12.Tag = Nothing
        ToolbarButton12.Text = "Menu"
        ToolbarButton12.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton12.ToolTips = ""
        ToolbarButton12.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton12.Visible = True
        ToolbarButton12.Width = 47
        ToolbarButton13.BackColor = System.Drawing.Color.Empty
        ToolbarButton13.BorderColor = System.Drawing.Color.Silver
        ToolbarButton13.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton13.BorderVisible = False
        ToolbarButton13.CheckStyle = iControl.ToolbarButton.eCheckStyle.Check
        ToolbarButton13.CloseDropDownMenuAfterCheckBoxClick = True
        ToolbarButton13.CloseDropDownMenuAfterSubItemsClick = True
        ToolbarButton13.DefaultFont = Nothing
        ToolbarButton13.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton13.DefaultRowItemHeight = 0
        ToolbarButton13.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton13.DefaultTitleFont = Nothing
        ToolbarButton13.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton13.DropDown = False
        ToolbarButton13.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton13.DropDownMenuColoumnsCount = 1
        ToolbarButton13.Enabled = True
        ToolbarButton13.EnabledFirstDisplaySubItemSelected = True
        ToolbarButton13.EnableSubItemsSelection = True
        ToolbarButton13.Font = Nothing
        ToolbarButton13.ForeColor = System.Drawing.Color.Empty
        ToolbarButton13.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton13.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton13.FullRowSelect = False
        ToolbarButton13.Image = Nothing
        ToolbarButton13.Index = 12
        ToolbarButton13.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton13.InternalBorderVisible = False
        ToolbarButton13.MaxDropDownItems = 0
        ToolbarButton13.MaxSubWidth = -1
        ToolbarButton13.MaxWidth = -1
        ToolbarButton13.MenuHorizontalAlignment = -1
        ToolbarButton13.MenuVerticalAlignment = -1
        ToolbarButton13.MinSubWidth = -1
        ToolbarButton13.MinWidth = -1
        ToolbarButton13.Name = ""
        ToolbarButton13.RowsHeightAutoSize = True
        ToolbarButton13.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton13.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton13.ShowColumnCheck = False
        ToolbarButton13.ShowColumnImage = False
        ToolbarButton13.State = False
        ToolbarButton13.SubButtonsContextMenuStrip = Nothing
        ToolbarButton13.SubColumnWidth = Nothing
        ToolbarButton13.SubHeight = 100
        ToolbarButton13.SubItemsAutoSize = False
        ToolbarButton13.SubWidth = 100
        ToolbarButton13.Tag = Nothing
        ToolbarButton13.Text = "Menu"
        ToolbarButton13.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton13.ToolTips = ""
        ToolbarButton13.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton13.Visible = True
        ToolbarButton13.Width = 47
        ToolbarButton14.BackColor = System.Drawing.Color.Empty
        ToolbarButton14.BorderColor = System.Drawing.Color.Silver
        ToolbarButton14.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton14.BorderVisible = False
        ToolbarButton14.CheckStyle = iControl.ToolbarButton.eCheckStyle.Check
        ToolbarButton14.CloseDropDownMenuAfterCheckBoxClick = True
        ToolbarButton14.CloseDropDownMenuAfterSubItemsClick = True
        ToolbarButton14.DefaultFont = Nothing
        ToolbarButton14.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton14.DefaultRowItemHeight = 0
        ToolbarButton14.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton14.DefaultTitleFont = Nothing
        ToolbarButton14.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton14.DropDown = False
        ToolbarButton14.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton14.DropDownMenuColoumnsCount = 1
        ToolbarButton14.Enabled = True
        ToolbarButton14.EnabledFirstDisplaySubItemSelected = True
        ToolbarButton14.EnableSubItemsSelection = True
        ToolbarButton14.Font = Nothing
        ToolbarButton14.ForeColor = System.Drawing.Color.Empty
        ToolbarButton14.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton14.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton14.FullRowSelect = False
        ToolbarButton14.Image = Nothing
        ToolbarButton14.Index = 13
        ToolbarButton14.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton14.InternalBorderVisible = False
        ToolbarButton14.MaxDropDownItems = 0
        ToolbarButton14.MaxSubWidth = -1
        ToolbarButton14.MaxWidth = -1
        ToolbarButton14.MenuHorizontalAlignment = -1
        ToolbarButton14.MenuVerticalAlignment = -1
        ToolbarButton14.MinSubWidth = -1
        ToolbarButton14.MinWidth = -1
        ToolbarButton14.Name = ""
        ToolbarButton14.RowsHeightAutoSize = True
        ToolbarButton14.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton14.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton14.ShowColumnCheck = False
        ToolbarButton14.ShowColumnImage = False
        ToolbarButton14.State = False
        ToolbarButton14.SubButtonsContextMenuStrip = Nothing
        ToolbarButton14.SubColumnWidth = Nothing
        ToolbarButton14.SubHeight = 100
        ToolbarButton14.SubItemsAutoSize = False
        ToolbarButton14.SubWidth = 100
        ToolbarButton14.Tag = Nothing
        ToolbarButton14.Text = "Menu"
        ToolbarButton14.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton14.ToolTips = ""
        ToolbarButton14.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton14.Visible = True
        ToolbarButton14.Width = 47
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton1)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton2)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton3)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton4)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton5)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton6)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton7)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton8)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton9)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton10)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton11)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton12)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton13)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton14)
        Me.IForm1.WindowMenu.Dull = False
        Me.IForm1.WindowMenu.EnabledSelection = False
        Me.IForm1.WindowMenu.FillControl = False
        Me.IForm1.WindowMenu.FlatStyle = False
        Me.IForm1.WindowMenu.Font = New System.Drawing.Font("Arial", 8.25!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.IForm1.WindowMenu.ForeColor = System.Drawing.Color.DimGray
        Me.IForm1.WindowMenu.ForeColorDropDown = System.Drawing.Color.DimGray
        Me.IForm1.WindowMenu.ForeColorSelect = System.Drawing.Color.DimGray
        Me.IForm1.WindowMenu.Location = New System.Drawing.Point(48, 15)
        Me.IForm1.WindowMenu.MaxDropDownItems = 8
        Me.IForm1.WindowMenu.MenuHorizontalAlignment = 0
        Me.IForm1.WindowMenu.MenuVerticalAlignment = 0
        Me.IForm1.WindowMenu.MultiSelection = False
        Me.IForm1.WindowMenu.Name = "tlbmenu"
        Me.IForm1.WindowMenu.ReadOnly = False
        Me.IForm1.WindowMenu.SelectionColor = System.Drawing.Color.White
        Me.IForm1.WindowMenu.SelectionColorDropDown = System.Drawing.Color.White
        Me.IForm1.WindowMenu.SeparatorColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.IForm1.WindowMenu.Size = New System.Drawing.Size(661, 24)
        Me.IForm1.WindowMenu.SubItemsMultiSelection = False
        Me.IForm1.WindowMenu.SuspundeLayout = False
        Me.IForm1.WindowMenu.TabIndex = 160
        Me.IForm1.WindowMenu.TextAntiAlis = False
        Me.IForm1.WindowMenu.TextGlowEffetct = False
        Me.IForm1.WindowMenu.TextShadows = False
        Me.IForm1.WindowMenu.ToolbarBorderColor = System.Drawing.Color.DimGray
        Me.IForm1.WindowMenu.ToolbarBorderVisible = False
        Me.IForm1.WindowMenu.ToolbarPadding = 1
        Me.IForm1.WindowMenu.ToolTipDown = True
        Me.IForm1.WindowMenu.Visible = False
        Me.IForm1.WindowMenuLeft = 9
        Me.IForm1.WindowMenuMinWidth = -1
        Me.IForm1.WindowMenuPadding = 9
        Me.IForm1.WindowsClipping = True
        Me.IForm1.WindowsTitle = "Update"
        '
        'dtg1
        '
        Me.dtg1.AllowUserToAddRows = False
        Me.dtg1.AllowUserToDeleteRows = False
        Me.dtg1.AllowUserToResizeColumns = False
        Me.dtg1.AllowUserToResizeRows = False
        Me.dtg1.BackgroundColor = System.Drawing.Color.White
        Me.dtg1.BorderColor = System.Drawing.Color.DarkGray
        Me.dtg1.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D
        Me.dtg1.BorderVisible = True
        Me.dtg1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.None
        DataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        DataGridViewCellStyle1.BackColor = System.Drawing.Color.Gainsboro
        DataGridViewCellStyle1.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.8!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel, CType(0, Byte))
        DataGridViewCellStyle1.ForeColor = System.Drawing.SystemColors.WindowText
        DataGridViewCellStyle1.SelectionBackColor = System.Drawing.SystemColors.Highlight
        DataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText
        Me.dtg1.ColumnHeadersDefaultCellStyle = DataGridViewCellStyle1
        Me.dtg1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.dtg1.ColumnHeadersVisible = False
        Me.dtg1.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.Column1})
        Me.dtg1.CustomHeaderBarSeparateColor2 = System.Drawing.Color.Silver
        Me.dtg1.CustomHeaderColor1 = System.Drawing.Color.LightGray
        Me.dtg1.CustomHeaderColor2 = System.Drawing.Color.DarkGray
        DataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.TopLeft
        DataGridViewCellStyle2.BackColor = System.Drawing.Color.White
        DataGridViewCellStyle2.Font = New System.Drawing.Font("Arial", 11.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel)
        DataGridViewCellStyle2.ForeColor = System.Drawing.Color.DimGray
        DataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.Transparent
        DataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White
        DataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.[True]
        Me.dtg1.DefaultCellStyle = DataGridViewCellStyle2
        Me.dtg1.Dull = True
        Me.dtg1.EditMode = System.Windows.Forms.DataGridViewEditMode.EditProgrammatically
        Me.dtg1.EnabledCustomCurrentCell = False
        Me.dtg1.EnabledCustomSelectStyle = True
        Me.dtg1.FlatStyle = False
        Me.dtg1.GridColor = System.Drawing.Color.Gainsboro
        Me.dtg1.InternalBorderColor = System.Drawing.Color.White
        Me.dtg1.InternalBorderVisible = True
        Me.dtg1.Location = New System.Drawing.Point(265, 81)
        Me.dtg1.Margin = New System.Windows.Forms.Padding(4)
        Me.dtg1.MultiSelect = False
        Me.dtg1.Name = "dtg1"
        DataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        DataGridViewCellStyle3.BackColor = System.Drawing.Color.Gainsboro
        DataGridViewCellStyle3.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        DataGridViewCellStyle3.ForeColor = System.Drawing.SystemColors.WindowText
        DataGridViewCellStyle3.SelectionBackColor = System.Drawing.SystemColors.Highlight
        DataGridViewCellStyle3.SelectionForeColor = System.Drawing.SystemColors.HighlightText
        DataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.[True]
        Me.dtg1.RowHeadersDefaultCellStyle = DataGridViewCellStyle3
        Me.dtg1.RowHeadersVisible = False
        Me.dtg1.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
        DataGridViewCellStyle4.Padding = New System.Windows.Forms.Padding(3)
        DataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.[True]
        Me.dtg1.RowsDefaultCellStyle = DataGridViewCellStyle4
        Me.dtg1.RowTemplate.DefaultCellStyle.WrapMode = System.Windows.Forms.DataGridViewTriState.[True]
        Me.dtg1.ScrollBars = System.Windows.Forms.ScrollBars.Vertical
        Me.dtg1.SelectionCellBorderStyle = iControl.iDataGridView.eSelectionBorderCell.LeftAndTopAndBottom
        Me.dtg1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
        Me.dtg1.Size = New System.Drawing.Size(65, 40)
        Me.dtg1.TabIndex = 19
        Me.dtg1.TextAntiAlis = False
        Me.dtg1.Visible = False
        '
        'Column1
        '
        Me.Column1.HeaderText = ""
        Me.Column1.Name = "Column1"
        Me.Column1.Width = 600
        '
        'frmupdate
        '
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None
        Me.BackColor = System.Drawing.Color.White
        Me.ClientSize = New System.Drawing.Size(344, 134)
        Me.Controls.Add(Me.dtg1)
        Me.Controls.Add(Me.ILabel2)
        Me.Controls.Add(Me.ILabel1)
        Me.Controls.Add(Me.IButton1)
        Me.Controls.Add(Me.IButton2)
        Me.Controls.Add(Me.IForm1)
        Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None
        Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
        Me.Margin = New System.Windows.Forms.Padding(4)
        Me.Name = "frmupdate"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "Update"
        Me.TopMost = True
        CType(Me.dtg1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)

    End Sub
    Friend WithEvents IForm1 As iControl.iForm
    Friend WithEvents IButton2 As iControl.iButton
    Friend WithEvents IButton1 As iControl.iButton
    Friend WithEvents ILabel1 As iControl.iLabel
    Friend WithEvents ILabel2 As iControl.iLabel
    Friend WithEvents dtg1 As iControl.iDataGridView
    Friend WithEvents Column1 As System.Windows.Forms.DataGridViewTextBoxColumn
End Class
