<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmupdateserver
    Inherits iFantaForm

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing AndAlso components IsNot Nothing Then
            components.Dispose()
        End If
        MyBase.Dispose(disposing)
    End Sub

    'Richiesto da Progettazione Windows Form
    Private components As System.ComponentModel.IContainer

    'NOTA: la procedura che segue è richiesta da Progettazione Windows Form
    'Può essere modificata in Progettazione Windows Form.  
    'Non modificarla nell'editor del codice.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmupdateserver))
        Dim ToolbarButton1 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton2 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ILinePen1 As iControl.iLinePen = New iControl.iLinePen()
        Dim ToolbarButton3 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton4 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton5 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton6 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton7 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton8 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton9 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton10 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton11 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton12 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton13 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton14 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton15 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton16 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton17 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton18 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton19 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton20 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton21 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton22 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton23 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Dim ToolbarButton24 As iControl.ToolbarButton = New iControl.ToolbarButton()
        Me.tlbaction = New iControl.iToolBar()
        Me.lbby = New iControl.iLabel()
        Me.lbtorneo1 = New iControl.iLabel()
        Me.lbtorneo2 = New iControl.iLabel()
        Me.lbmain = New iControl.iLabel()
        Me.pic1 = New System.Windows.Forms.PictureBox()
        Me.chkimg = New iControl.iCheckBox()
        Me.chkdata = New iControl.iCheckBox()
        Me.chkconf = New iControl.iCheckBox()
        Me.prb1 = New iControl.iProgressBar()
        Me.ILine1 = New iControl.iLine()
        Me.IForm1 = New iControl.iForm()
        Me.lbstatus = New System.Windows.Forms.Label()
        Me.chkopt = New iControl.iCheckBox()
        CType(Me.pic1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'tlbaction
        '
        Me.tlbaction.Anchor = CType((System.Windows.Forms.AnchorStyles.Bottom Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.tlbaction.AutoSize = True
        Me.tlbaction.AutoSizeMaxWidth = -1.0!
        Me.tlbaction.AutoSizeMinWidth = -1.0!
        Me.tlbaction.Background = Nothing
        Me.tlbaction.BackgroundImage = CType(resources.GetObject("tlbaction.BackgroundImage"), System.Drawing.Image)
        Me.tlbaction.BorderColor = System.Drawing.Color.DimGray
        Me.tlbaction.BorderColorDropDown = System.Drawing.Color.DimGray
        ToolbarButton1.BackColor = System.Drawing.Color.Empty
        ToolbarButton1.BorderColor = System.Drawing.Color.Empty
        ToolbarButton1.BorderColorDropDown = System.Drawing.Color.Empty
        ToolbarButton1.BorderVisible = False
        ToolbarButton1.DefaultFont = Nothing
        ToolbarButton1.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton1.DefaultRowItemHeight = 0
        ToolbarButton1.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton1.DefaultTitleFont = Nothing
        ToolbarButton1.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton1.DropDown = False
        ToolbarButton1.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton1.DropDownMenuColoumnsCount = 1
        ToolbarButton1.Enabled = True
        ToolbarButton1.EnableSubItemsSelection = True
        ToolbarButton1.Font = Nothing
        ToolbarButton1.ForeColor = System.Drawing.Color.Empty
        ToolbarButton1.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton1.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton1.FullRowSelect = False
        ToolbarButton1.Image = Global.iFanta.My.Resources.Resources.reload16
        ToolbarButton1.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton1.InternalBorderVisible = False
        ToolbarButton1.MaxDropDownItems = 0
        ToolbarButton1.MaxSubWidth = -1
        ToolbarButton1.MaxWidth = -1
        ToolbarButton1.MenuHorizontalAlignment = -1
        ToolbarButton1.MenuVerticalAlignment = -1
        ToolbarButton1.MinSubWidth = -1
        ToolbarButton1.MinWidth = -1
        ToolbarButton1.Name = ""
        ToolbarButton1.RowsHeightAutoSize = True
        ToolbarButton1.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton1.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton1.ShowColumnCheck = False
        ToolbarButton1.ShowColumnImage = False
        ToolbarButton1.State = False
        ToolbarButton1.SubColumnWidth = CType(resources.GetObject("ToolbarButton1.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton1.SubHeight = 100
        ToolbarButton1.SubItemsAutoSize = True
        ToolbarButton1.SubWidth = 100
        ToolbarButton1.Tag = Nothing
        ToolbarButton1.Text = "Aggiorna"
        ToolbarButton1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton1.ToolTips = ""
        ToolbarButton1.Type = iControl.ToolbarButton.iType.Button
        ToolbarButton1.Visible = True
        ToolbarButton1.Width = 75
        ToolbarButton2.BackColor = System.Drawing.Color.Empty
        ToolbarButton2.BorderColor = System.Drawing.Color.Empty
        ToolbarButton2.BorderColorDropDown = System.Drawing.Color.Empty
        ToolbarButton2.BorderVisible = False
        ToolbarButton2.DefaultFont = Nothing
        ToolbarButton2.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton2.DefaultRowItemHeight = 0
        ToolbarButton2.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton2.DefaultTitleFont = Nothing
        ToolbarButton2.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton2.DropDown = False
        ToolbarButton2.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton2.DropDownMenuColoumnsCount = 1
        ToolbarButton2.Enabled = True
        ToolbarButton2.EnableSubItemsSelection = True
        ToolbarButton2.Font = Nothing
        ToolbarButton2.ForeColor = System.Drawing.Color.Empty
        ToolbarButton2.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton2.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton2.FullRowSelect = False
        ToolbarButton2.Image = Global.iFanta.My.Resources.Resources.closer16
        ToolbarButton2.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton2.InternalBorderVisible = False
        ToolbarButton2.MaxDropDownItems = 0
        ToolbarButton2.MaxSubWidth = -1
        ToolbarButton2.MaxWidth = -1
        ToolbarButton2.MenuHorizontalAlignment = -1
        ToolbarButton2.MenuVerticalAlignment = -1
        ToolbarButton2.MinSubWidth = -1
        ToolbarButton2.MinWidth = -1
        ToolbarButton2.Name = ""
        ToolbarButton2.RowsHeightAutoSize = True
        ToolbarButton2.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton2.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton2.ShowColumnCheck = False
        ToolbarButton2.ShowColumnImage = False
        ToolbarButton2.State = False
        ToolbarButton2.SubColumnWidth = CType(resources.GetObject("ToolbarButton2.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton2.SubHeight = 100
        ToolbarButton2.SubItemsAutoSize = False
        ToolbarButton2.SubWidth = 100
        ToolbarButton2.Tag = Nothing
        ToolbarButton2.Text = "Chiudi"
        ToolbarButton2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton2.ToolTips = ""
        ToolbarButton2.Type = iControl.ToolbarButton.iType.Button
        ToolbarButton2.Visible = True
        ToolbarButton2.Width = 63
        Me.tlbaction.Button.Add(ToolbarButton1)
        Me.tlbaction.Button.Add(ToolbarButton2)
        Me.tlbaction.Dull = False
        Me.tlbaction.EnabledSelection = False
        Me.tlbaction.FlatStyle = False
        Me.tlbaction.Font = New System.Drawing.Font("Arial", 11.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel, CType(0, Byte))
        Me.tlbaction.ForeColor = System.Drawing.Color.FromArgb(CType(CType(50, Byte), Integer), CType(CType(50, Byte), Integer), CType(CType(50, Byte), Integer))
        Me.tlbaction.ForeColorDropDown = System.Drawing.Color.FromArgb(CType(CType(50, Byte), Integer), CType(CType(50, Byte), Integer), CType(CType(50, Byte), Integer))
        Me.tlbaction.ForeColorSelect = System.Drawing.Color.Red
        Me.tlbaction.Location = New System.Drawing.Point(277, 312)
        Me.tlbaction.MaxDropDownItems = 15
        Me.tlbaction.MenuHorizontalAlignment = 1
        Me.tlbaction.MenuVerticalAlignment = 0
        Me.tlbaction.MultiSelection = False
        Me.tlbaction.Name = "tlbaction"
        Me.tlbaction.ReadOnly = False
        Me.tlbaction.SelectionColor = System.Drawing.Color.White
        Me.tlbaction.SelectionColorDropDown = System.Drawing.Color.White
        Me.tlbaction.SeparatorColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.tlbaction.Size = New System.Drawing.Size(139, 19)
        Me.tlbaction.SubItemsMultiSelection = False
        Me.tlbaction.SuspundeLayout = False
        Me.tlbaction.TabIndex = 281
        Me.tlbaction.TextAntiAlis = False
        Me.tlbaction.TextGlowEffetct = False
        Me.tlbaction.TextShadows = False
        Me.tlbaction.ToolbarBorderColor = System.Drawing.Color.DimGray
        Me.tlbaction.ToolbarBorderVisible = False
        Me.tlbaction.ToolbarPadding = 0
        Me.tlbaction.ToolTipDown = True
        '
        'lbby
        '
        Me.lbby.Anchor = CType((System.Windows.Forms.AnchorStyles.Bottom Or System.Windows.Forms.AnchorStyles.Left), System.Windows.Forms.AnchorStyles)
        Me.lbby.AutoSizeStyle = iControl.iLabel.eAutoSizeStyle.OnlyWitdh
        Me.lbby.AutoValidate = System.Windows.Forms.AutoValidate.Disable
        Me.lbby.BackColor = System.Drawing.Color.White
        Me.lbby.Background = Nothing
        Me.lbby.BackgroundImage = CType(resources.GetObject("lbby.BackgroundImage"), System.Drawing.Image)
        Me.lbby.BorderColor = System.Drawing.Color.DimGray
        Me.lbby.BorderSize = 0
        Me.lbby.BorderVisible = False
        Me.lbby.Dull = False
        Me.lbby.Font = New System.Drawing.Font("Arial", 11.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel, CType(0, Byte))
        Me.lbby.ForeColor = System.Drawing.Color.DimGray
        Me.lbby.Image = Nothing
        Me.lbby.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.lbby.InternalBorderColor = System.Drawing.Color.White
        Me.lbby.InternalBorderSize = 0
        Me.lbby.LineAlignment = System.Drawing.StringAlignment.Center
        Me.lbby.Location = New System.Drawing.Point(23, 312)
        Me.lbby.Name = "lbby"
        Me.lbby.Size = New System.Drawing.Size(236, 19)
        Me.lbby.SuspundeLayout = False
        Me.lbby.TabIndex = 280
        Me.lbby.Text = "xxxx"
        Me.lbby.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.lbby.TextAntiAlis = False
        Me.lbby.TextGlowEffetct = False
        Me.lbby.TextShadows = False
        Me.lbby.TextVertical = False
        Me.lbby.ToolTip = ""
        Me.lbby.WordWrap = False
        '
        'lbtorneo1
        '
        Me.lbtorneo1.AutoSize = True
        Me.lbtorneo1.AutoSizeStyle = iControl.iLabel.eAutoSizeStyle.OnlyWitdh
        Me.lbtorneo1.AutoValidate = System.Windows.Forms.AutoValidate.Disable
        Me.lbtorneo1.Background = Nothing
        Me.lbtorneo1.BackgroundImage = CType(resources.GetObject("lbtorneo1.BackgroundImage"), System.Drawing.Image)
        Me.lbtorneo1.BorderColor = System.Drawing.Color.DimGray
        Me.lbtorneo1.BorderSize = 0
        Me.lbtorneo1.BorderVisible = False
        Me.lbtorneo1.Dull = False
        Me.lbtorneo1.Font = New System.Drawing.Font("Arial", 12.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel, CType(0, Byte))
        Me.lbtorneo1.ForeColor = System.Drawing.Color.White
        Me.lbtorneo1.Image = Nothing
        Me.lbtorneo1.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.lbtorneo1.InternalBorderColor = System.Drawing.Color.White
        Me.lbtorneo1.InternalBorderSize = 0
        Me.lbtorneo1.LineAlignment = System.Drawing.StringAlignment.Center
        Me.lbtorneo1.Location = New System.Drawing.Point(290, 28)
        Me.lbtorneo1.Name = "lbtorneo1"
        Me.lbtorneo1.Size = New System.Drawing.Size(57, 22)
        Me.lbtorneo1.SuspundeLayout = False
        Me.lbtorneo1.TabIndex = 279
        Me.lbtorneo1.Text = "Torneo :"
        Me.lbtorneo1.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        Me.lbtorneo1.TextAntiAlis = True
        Me.lbtorneo1.TextGlowEffetct = True
        Me.lbtorneo1.TextShadows = False
        Me.lbtorneo1.TextVertical = False
        Me.lbtorneo1.ToolTip = ""
        Me.lbtorneo1.Visible = False
        Me.lbtorneo1.WordWrap = False
        '
        'lbtorneo2
        '
        Me.lbtorneo2.AutoSize = True
        Me.lbtorneo2.AutoSizeStyle = iControl.iLabel.eAutoSizeStyle.OnlyWitdh
        Me.lbtorneo2.AutoValidate = System.Windows.Forms.AutoValidate.Disable
        Me.lbtorneo2.Background = Nothing
        Me.lbtorneo2.BackgroundImage = CType(resources.GetObject("lbtorneo2.BackgroundImage"), System.Drawing.Image)
        Me.lbtorneo2.BorderColor = System.Drawing.Color.DimGray
        Me.lbtorneo2.BorderSize = 0
        Me.lbtorneo2.BorderVisible = False
        Me.lbtorneo2.Dull = False
        Me.lbtorneo2.Font = New System.Drawing.Font("Arial", 15.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel, CType(0, Byte))
        Me.lbtorneo2.ForeColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.lbtorneo2.Image = Nothing
        Me.lbtorneo2.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.lbtorneo2.InternalBorderColor = System.Drawing.Color.White
        Me.lbtorneo2.InternalBorderSize = 0
        Me.lbtorneo2.LineAlignment = System.Drawing.StringAlignment.Center
        Me.lbtorneo2.Location = New System.Drawing.Point(361, 28)
        Me.lbtorneo2.Name = "lbtorneo2"
        Me.lbtorneo2.Size = New System.Drawing.Size(52, 22)
        Me.lbtorneo2.SuspundeLayout = False
        Me.lbtorneo2.TabIndex = 278
        Me.lbtorneo2.Text = "xxxxx"
        Me.lbtorneo2.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        Me.lbtorneo2.TextAntiAlis = True
        Me.lbtorneo2.TextGlowEffetct = True
        Me.lbtorneo2.TextShadows = False
        Me.lbtorneo2.TextVertical = False
        Me.lbtorneo2.ToolTip = ""
        Me.lbtorneo2.Visible = False
        Me.lbtorneo2.WordWrap = False
        '
        'lbmain
        '
        Me.lbmain.AutoSizeStyle = iControl.iLabel.eAutoSizeStyle.OnlyWitdh
        Me.lbmain.AutoValidate = System.Windows.Forms.AutoValidate.Disable
        Me.lbmain.Background = Nothing
        Me.lbmain.BackgroundImage = CType(resources.GetObject("lbmain.BackgroundImage"), System.Drawing.Image)
        Me.lbmain.BorderColor = System.Drawing.Color.DimGray
        Me.lbmain.BorderSize = 0
        Me.lbmain.BorderVisible = False
        Me.lbmain.Dull = False
        Me.lbmain.Font = New System.Drawing.Font("Arial", 16.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel, CType(0, Byte))
        Me.lbmain.ForeColor = System.Drawing.Color.DimGray
        Me.lbmain.Image = Nothing
        Me.lbmain.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.lbmain.InternalBorderColor = System.Drawing.Color.White
        Me.lbmain.InternalBorderSize = 0
        Me.lbmain.LineAlignment = System.Drawing.StringAlignment.Center
        Me.lbmain.Location = New System.Drawing.Point(79, 76)
        Me.lbmain.Name = "lbmain"
        Me.lbmain.Size = New System.Drawing.Size(309, 42)
        Me.lbmain.SuspundeLayout = False
        Me.lbmain.TabIndex = 277
        Me.lbmain.Text = "Aggiornamento dati torneo 2012-2013 "
        Me.lbmain.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.lbmain.TextAntiAlis = False
        Me.lbmain.TextGlowEffetct = False
        Me.lbmain.TextShadows = False
        Me.lbmain.TextVertical = False
        Me.lbmain.ToolTip = ""
        Me.lbmain.WordWrap = False
        '
        'pic1
        '
        Me.pic1.Image = Global.iFanta.My.Resources.Resources._12
        Me.pic1.Location = New System.Drawing.Point(23, 76)
        Me.pic1.Name = "pic1"
        Me.pic1.Size = New System.Drawing.Size(50, 53)
        Me.pic1.TabIndex = 276
        Me.pic1.TabStop = False
        '
        'chkimg
        '
        Me.chkimg.Alignment = System.Windows.Forms.HorizontalAlignment.Left
        Me.chkimg.Background = Nothing
        Me.chkimg.BackgroundImage = CType(resources.GetObject("chkimg.BackgroundImage"), System.Drawing.Image)
        Me.chkimg.BorderColor = System.Drawing.Color.DimGray
        Me.chkimg.BorderSize = 0
        Me.chkimg.BorderVisible = False
        Me.chkimg.Dull = False
        Me.chkimg.EnalbedStyleValueMode = False
        Me.chkimg.Font = New System.Drawing.Font("Arial", 11.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel, CType(0, Byte))
        Me.chkimg.ForeColor = System.Drawing.Color.FromArgb(CType(CType(80, Byte), Integer), CType(CType(80, Byte), Integer), CType(CType(80, Byte), Integer))
        Me.chkimg.LineAlignment = System.Drawing.StringAlignment.Center
        Me.chkimg.Location = New System.Drawing.Point(43, 204)
        Me.chkimg.Name = "chkimg"
        Me.chkimg.ReadOnly = False
        Me.chkimg.Size = New System.Drawing.Size(331, 20)
        Me.chkimg.SuspundeLayout = False
        Me.chkimg.TabIndex = 275
        Me.chkimg.Text = "Aggiorna stemmi squadre"
        Me.chkimg.TextAntiAlis = False
        Me.chkimg.TextGlowEffetct = False
        Me.chkimg.TextShadows = False
        Me.chkimg.Value = False
        Me.chkimg.WordWrap = False
        '
        'chkdata
        '
        Me.chkdata.Alignment = System.Windows.Forms.HorizontalAlignment.Left
        Me.chkdata.Background = Nothing
        Me.chkdata.BackgroundImage = CType(resources.GetObject("chkdata.BackgroundImage"), System.Drawing.Image)
        Me.chkdata.BorderColor = System.Drawing.Color.DimGray
        Me.chkdata.BorderSize = 0
        Me.chkdata.BorderVisible = False
        Me.chkdata.Dull = False
        Me.chkdata.EnalbedStyleValueMode = False
        Me.chkdata.Font = New System.Drawing.Font("Arial", 11.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel, CType(0, Byte))
        Me.chkdata.ForeColor = System.Drawing.Color.FromArgb(CType(CType(80, Byte), Integer), CType(CType(80, Byte), Integer), CType(CType(80, Byte), Integer))
        Me.chkdata.LineAlignment = System.Drawing.StringAlignment.Center
        Me.chkdata.Location = New System.Drawing.Point(43, 181)
        Me.chkdata.Name = "chkdata"
        Me.chkdata.ReadOnly = False
        Me.chkdata.Size = New System.Drawing.Size(331, 20)
        Me.chkdata.SuspundeLayout = False
        Me.chkdata.TabIndex = 271
        Me.chkdata.Text = "Aggiorna dati torneo (rose, formazioni ecc...)"
        Me.chkdata.TextAntiAlis = False
        Me.chkdata.TextGlowEffetct = False
        Me.chkdata.TextShadows = False
        Me.chkdata.Value = True
        Me.chkdata.WordWrap = False
        '
        'chkconf
        '
        Me.chkconf.Alignment = System.Windows.Forms.HorizontalAlignment.Left
        Me.chkconf.Background = Nothing
        Me.chkconf.BackgroundImage = CType(resources.GetObject("chkconf.BackgroundImage"), System.Drawing.Image)
        Me.chkconf.BorderColor = System.Drawing.Color.DimGray
        Me.chkconf.BorderSize = 0
        Me.chkconf.BorderVisible = False
        Me.chkconf.Dull = False
        Me.chkconf.EnalbedStyleValueMode = False
        Me.chkconf.Font = New System.Drawing.Font("Arial", 11.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel, CType(0, Byte))
        Me.chkconf.ForeColor = System.Drawing.Color.FromArgb(CType(CType(80, Byte), Integer), CType(CType(80, Byte), Integer), CType(CType(80, Byte), Integer))
        Me.chkconf.LineAlignment = System.Drawing.StringAlignment.Center
        Me.chkconf.Location = New System.Drawing.Point(43, 158)
        Me.chkconf.Name = "chkconf"
        Me.chkconf.ReadOnly = False
        Me.chkconf.Size = New System.Drawing.Size(331, 20)
        Me.chkconf.SuspundeLayout = False
        Me.chkconf.TabIndex = 270
        Me.chkconf.Text = "Aggiorna configurazioni torneo"
        Me.chkconf.TextAntiAlis = False
        Me.chkconf.TextGlowEffetct = False
        Me.chkconf.TextShadows = False
        Me.chkconf.Value = False
        Me.chkconf.WordWrap = False
        '
        'prb1
        '
        Me.prb1.Anchor = CType((System.Windows.Forms.AnchorStyles.Bottom Or System.Windows.Forms.AnchorStyles.Left), System.Windows.Forms.AnchorStyles)
        Me.prb1.BackColor = System.Drawing.Color.White
        Me.prb1.BarColor = System.Drawing.Color.Lime
        Me.prb1.BorderColor = System.Drawing.Color.Silver
        Me.prb1.Dull = False
        Me.prb1.FlatStyle = False
        Me.prb1.Location = New System.Drawing.Point(14, 268)
        Me.prb1.Max = 10.0R
        Me.prb1.Name = "prb1"
        Me.prb1.Size = New System.Drawing.Size(406, 17)
        Me.prb1.Smooth = True
        Me.prb1.SuspundeLayout = False
        Me.prb1.TabIndex = 269
        Me.prb1.Text = Nothing
        Me.prb1.Value = 0.0R
        '
        'ILine1
        '
        Me.ILine1.Anchor = CType((System.Windows.Forms.AnchorStyles.Bottom Or System.Windows.Forms.AnchorStyles.Left), System.Windows.Forms.AnchorStyles)
        Me.ILine1.BackgroundImage = CType(resources.GetObject("ILine1.BackgroundImage"), System.Drawing.Image)
        ILinePen1.Color = System.Drawing.Color.Gray
        ILinePen1.DashStyle = System.Drawing.Drawing2D.DashStyle.Dot
        ILinePen1.Width = 1
        Me.ILine1.Line = ILinePen1
        Me.ILine1.Location = New System.Drawing.Point(23, 291)
        Me.ILine1.Name = "ILine1"
        Me.ILine1.Size = New System.Drawing.Size(397, 10)
        Me.ILine1.SuspundeLayout = False
        Me.ILine1.TabIndex = 268
        Me.ILine1.TextAntiAlis = True
        Me.ILine1.TextShadows = False
        '
        'IForm1
        '
        Me.IForm1.BH1 = 0
        Me.IForm1.BH2 = 0
        Me.IForm1.BH3 = 0
        Me.IForm1.BH4 = 0
        Me.IForm1.BH5 = 0
        Me.IForm1.BH6 = 0
        Me.IForm1.CloseButton = True
        Me.IForm1.ControlBox = True
        Me.IForm1.Dock = System.Windows.Forms.DockStyle.Fill
        Me.IForm1.FlatStyle = False
        Me.IForm1.FontTitleWindows = New System.Drawing.Font("Arial", 12.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel)
        Me.IForm1.ForeColorTitleWindows = System.Drawing.Color.White
        Me.IForm1.Icon = Nothing
        Me.IForm1.Location = New System.Drawing.Point(0, 0)
        Me.IForm1.LogoLeft = Nothing
        Me.IForm1.LogoRight = CType(resources.GetObject("IForm1.LogoRight"), System.Drawing.Image)
        Me.IForm1.MaximizeButton = False
        Me.IForm1.MinimizeButton = False
        Me.IForm1.Movable = True
        Me.IForm1.Name = "IForm1"
        Me.IForm1.Rel = ""
        Me.IForm1.ResizeType = iControl.iForm.eResizeType.All
        Me.IForm1.ShowBottomBar1 = True
        Me.IForm1.ShowBottomBar2 = True
        Me.IForm1.ShowBottomBar3 = True
        Me.IForm1.ShowBottomBarSeparator1 = True
        Me.IForm1.ShowBottomBarSeparator2 = True
        Me.IForm1.ShowBottomBarSeparator3 = False
        Me.IForm1.ShowLogoLeft = True
        Me.IForm1.ShowLogoRight = False
        Me.IForm1.ShowSystemMenu = True
        Me.IForm1.ShowTopBar1 = True
        Me.IForm1.ShowTopBar2 = True
        Me.IForm1.ShowTopBar3 = True
        Me.IForm1.ShowTopBarSeparator1 = False
        Me.IForm1.ShowTopBarSeparator2 = True
        Me.IForm1.ShowTopBarSeparator3 = True
        Me.IForm1.Sizable = False
        Me.IForm1.Size = New System.Drawing.Size(441, 351)
        Me.IForm1.SuspundeLayout = False
        Me.IForm1.TabIndex = 267
        Me.IForm1.TH1 = 30
        Me.IForm1.TH2 = 1
        Me.IForm1.TH3 = 5
        Me.IForm1.TH4 = 1
        Me.IForm1.TH5 = 0
        Me.IForm1.TH6 = 0
        Me.IForm1.Theme = "Red"
        Me.IForm1.Title = "Aggiornamento dati server"
        Me.IForm1.TitleAlign = iControl.iForm.align.Left
        '
        '
        '
        Me.IForm1.WindowMenu.AutoSize = True
        Me.IForm1.WindowMenu.AutoSizeMaxWidth = -1.0!
        Me.IForm1.WindowMenu.AutoSizeMinWidth = -1.0!
        Me.IForm1.WindowMenu.BackColor = System.Drawing.Color.White
        Me.IForm1.WindowMenu.Background = Nothing
        Me.IForm1.WindowMenu.BackgroundImage = CType(resources.GetObject("resource.BackgroundImage"), System.Drawing.Image)
        Me.IForm1.WindowMenu.BorderColor = System.Drawing.Color.Gray
        Me.IForm1.WindowMenu.BorderColorDropDown = System.Drawing.Color.Gray
        ToolbarButton3.BackColor = System.Drawing.Color.Empty
        ToolbarButton3.BorderColor = System.Drawing.Color.Silver
        ToolbarButton3.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton3.BorderVisible = False
        ToolbarButton3.DefaultFont = Nothing
        ToolbarButton3.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton3.DefaultRowItemHeight = 0
        ToolbarButton3.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton3.DefaultTitleFont = Nothing
        ToolbarButton3.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton3.DropDown = False
        ToolbarButton3.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton3.DropDownMenuColoumnsCount = 1
        ToolbarButton3.Enabled = True
        ToolbarButton3.EnableSubItemsSelection = True
        ToolbarButton3.Font = Nothing
        ToolbarButton3.ForeColor = System.Drawing.Color.Empty
        ToolbarButton3.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton3.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton3.FullRowSelect = False
        ToolbarButton3.Image = Nothing
        ToolbarButton3.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton3.InternalBorderVisible = False
        ToolbarButton3.MaxDropDownItems = 0
        ToolbarButton3.MaxSubWidth = -1
        ToolbarButton3.MaxWidth = -1
        ToolbarButton3.MenuHorizontalAlignment = -1
        ToolbarButton3.MenuVerticalAlignment = -1
        ToolbarButton3.MinSubWidth = -1
        ToolbarButton3.MinWidth = -1
        ToolbarButton3.Name = ""
        ToolbarButton3.RowsHeightAutoSize = True
        ToolbarButton3.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton3.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton3.ShowColumnCheck = False
        ToolbarButton3.ShowColumnImage = False
        ToolbarButton3.State = False
        ToolbarButton3.SubColumnWidth = CType(resources.GetObject("ToolbarButton3.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton3.SubHeight = 100
        ToolbarButton3.SubItemsAutoSize = False
        ToolbarButton3.SubWidth = 100
        ToolbarButton3.Tag = Nothing
        ToolbarButton3.Text = "Menu"
        ToolbarButton3.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton3.ToolTips = ""
        ToolbarButton3.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton3.Visible = True
        ToolbarButton3.Width = 47
        ToolbarButton4.BackColor = System.Drawing.Color.Empty
        ToolbarButton4.BorderColor = System.Drawing.Color.Silver
        ToolbarButton4.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton4.BorderVisible = False
        ToolbarButton4.DefaultFont = Nothing
        ToolbarButton4.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton4.DefaultRowItemHeight = 0
        ToolbarButton4.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton4.DefaultTitleFont = Nothing
        ToolbarButton4.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton4.DropDown = False
        ToolbarButton4.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton4.DropDownMenuColoumnsCount = 1
        ToolbarButton4.Enabled = True
        ToolbarButton4.EnableSubItemsSelection = True
        ToolbarButton4.Font = Nothing
        ToolbarButton4.ForeColor = System.Drawing.Color.Empty
        ToolbarButton4.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton4.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton4.FullRowSelect = False
        ToolbarButton4.Image = Nothing
        ToolbarButton4.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton4.InternalBorderVisible = False
        ToolbarButton4.MaxDropDownItems = 0
        ToolbarButton4.MaxSubWidth = -1
        ToolbarButton4.MaxWidth = -1
        ToolbarButton4.MenuHorizontalAlignment = -1
        ToolbarButton4.MenuVerticalAlignment = -1
        ToolbarButton4.MinSubWidth = -1
        ToolbarButton4.MinWidth = -1
        ToolbarButton4.Name = ""
        ToolbarButton4.RowsHeightAutoSize = True
        ToolbarButton4.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton4.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton4.ShowColumnCheck = False
        ToolbarButton4.ShowColumnImage = False
        ToolbarButton4.State = False
        ToolbarButton4.SubColumnWidth = CType(resources.GetObject("ToolbarButton4.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton4.SubHeight = 100
        ToolbarButton4.SubItemsAutoSize = False
        ToolbarButton4.SubWidth = 100
        ToolbarButton4.Tag = Nothing
        ToolbarButton4.Text = "Menu"
        ToolbarButton4.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton4.ToolTips = ""
        ToolbarButton4.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton4.Visible = True
        ToolbarButton4.Width = 47
        ToolbarButton5.BackColor = System.Drawing.Color.Empty
        ToolbarButton5.BorderColor = System.Drawing.Color.Silver
        ToolbarButton5.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton5.BorderVisible = False
        ToolbarButton5.DefaultFont = Nothing
        ToolbarButton5.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton5.DefaultRowItemHeight = 0
        ToolbarButton5.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton5.DefaultTitleFont = Nothing
        ToolbarButton5.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton5.DropDown = False
        ToolbarButton5.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton5.DropDownMenuColoumnsCount = 1
        ToolbarButton5.Enabled = True
        ToolbarButton5.EnableSubItemsSelection = True
        ToolbarButton5.Font = Nothing
        ToolbarButton5.ForeColor = System.Drawing.Color.Empty
        ToolbarButton5.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton5.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton5.FullRowSelect = False
        ToolbarButton5.Image = Nothing
        ToolbarButton5.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton5.InternalBorderVisible = False
        ToolbarButton5.MaxDropDownItems = 0
        ToolbarButton5.MaxSubWidth = -1
        ToolbarButton5.MaxWidth = -1
        ToolbarButton5.MenuHorizontalAlignment = -1
        ToolbarButton5.MenuVerticalAlignment = -1
        ToolbarButton5.MinSubWidth = -1
        ToolbarButton5.MinWidth = -1
        ToolbarButton5.Name = ""
        ToolbarButton5.RowsHeightAutoSize = True
        ToolbarButton5.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton5.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton5.ShowColumnCheck = False
        ToolbarButton5.ShowColumnImage = False
        ToolbarButton5.State = False
        ToolbarButton5.SubColumnWidth = CType(resources.GetObject("ToolbarButton5.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton5.SubHeight = 100
        ToolbarButton5.SubItemsAutoSize = False
        ToolbarButton5.SubWidth = 100
        ToolbarButton5.Tag = Nothing
        ToolbarButton5.Text = "Menu"
        ToolbarButton5.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton5.ToolTips = ""
        ToolbarButton5.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton5.Visible = True
        ToolbarButton5.Width = 47
        ToolbarButton6.BackColor = System.Drawing.Color.Empty
        ToolbarButton6.BorderColor = System.Drawing.Color.Silver
        ToolbarButton6.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton6.BorderVisible = False
        ToolbarButton6.DefaultFont = Nothing
        ToolbarButton6.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton6.DefaultRowItemHeight = 0
        ToolbarButton6.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton6.DefaultTitleFont = Nothing
        ToolbarButton6.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton6.DropDown = False
        ToolbarButton6.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton6.DropDownMenuColoumnsCount = 1
        ToolbarButton6.Enabled = True
        ToolbarButton6.EnableSubItemsSelection = True
        ToolbarButton6.Font = Nothing
        ToolbarButton6.ForeColor = System.Drawing.Color.Empty
        ToolbarButton6.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton6.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton6.FullRowSelect = False
        ToolbarButton6.Image = Nothing
        ToolbarButton6.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton6.InternalBorderVisible = False
        ToolbarButton6.MaxDropDownItems = 0
        ToolbarButton6.MaxSubWidth = -1
        ToolbarButton6.MaxWidth = -1
        ToolbarButton6.MenuHorizontalAlignment = -1
        ToolbarButton6.MenuVerticalAlignment = -1
        ToolbarButton6.MinSubWidth = -1
        ToolbarButton6.MinWidth = -1
        ToolbarButton6.Name = ""
        ToolbarButton6.RowsHeightAutoSize = True
        ToolbarButton6.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton6.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton6.ShowColumnCheck = False
        ToolbarButton6.ShowColumnImage = False
        ToolbarButton6.State = False
        ToolbarButton6.SubColumnWidth = CType(resources.GetObject("ToolbarButton6.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton6.SubHeight = 100
        ToolbarButton6.SubItemsAutoSize = False
        ToolbarButton6.SubWidth = 100
        ToolbarButton6.Tag = Nothing
        ToolbarButton6.Text = "Menu"
        ToolbarButton6.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton6.ToolTips = ""
        ToolbarButton6.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton6.Visible = True
        ToolbarButton6.Width = 47
        ToolbarButton7.BackColor = System.Drawing.Color.Empty
        ToolbarButton7.BorderColor = System.Drawing.Color.Silver
        ToolbarButton7.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton7.BorderVisible = False
        ToolbarButton7.DefaultFont = Nothing
        ToolbarButton7.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton7.DefaultRowItemHeight = 0
        ToolbarButton7.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton7.DefaultTitleFont = Nothing
        ToolbarButton7.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton7.DropDown = False
        ToolbarButton7.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton7.DropDownMenuColoumnsCount = 1
        ToolbarButton7.Enabled = True
        ToolbarButton7.EnableSubItemsSelection = True
        ToolbarButton7.Font = Nothing
        ToolbarButton7.ForeColor = System.Drawing.Color.Empty
        ToolbarButton7.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton7.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton7.FullRowSelect = False
        ToolbarButton7.Image = Nothing
        ToolbarButton7.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton7.InternalBorderVisible = False
        ToolbarButton7.MaxDropDownItems = 0
        ToolbarButton7.MaxSubWidth = -1
        ToolbarButton7.MaxWidth = -1
        ToolbarButton7.MenuHorizontalAlignment = -1
        ToolbarButton7.MenuVerticalAlignment = -1
        ToolbarButton7.MinSubWidth = -1
        ToolbarButton7.MinWidth = -1
        ToolbarButton7.Name = ""
        ToolbarButton7.RowsHeightAutoSize = True
        ToolbarButton7.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton7.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton7.ShowColumnCheck = False
        ToolbarButton7.ShowColumnImage = False
        ToolbarButton7.State = False
        ToolbarButton7.SubColumnWidth = CType(resources.GetObject("ToolbarButton7.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton7.SubHeight = 100
        ToolbarButton7.SubItemsAutoSize = False
        ToolbarButton7.SubWidth = 100
        ToolbarButton7.Tag = Nothing
        ToolbarButton7.Text = "Menu"
        ToolbarButton7.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton7.ToolTips = ""
        ToolbarButton7.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton7.Visible = True
        ToolbarButton7.Width = 47
        ToolbarButton8.BackColor = System.Drawing.Color.Empty
        ToolbarButton8.BorderColor = System.Drawing.Color.Silver
        ToolbarButton8.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton8.BorderVisible = False
        ToolbarButton8.DefaultFont = Nothing
        ToolbarButton8.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton8.DefaultRowItemHeight = 0
        ToolbarButton8.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton8.DefaultTitleFont = Nothing
        ToolbarButton8.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton8.DropDown = False
        ToolbarButton8.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton8.DropDownMenuColoumnsCount = 1
        ToolbarButton8.Enabled = True
        ToolbarButton8.EnableSubItemsSelection = True
        ToolbarButton8.Font = Nothing
        ToolbarButton8.ForeColor = System.Drawing.Color.Empty
        ToolbarButton8.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton8.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton8.FullRowSelect = False
        ToolbarButton8.Image = Nothing
        ToolbarButton8.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton8.InternalBorderVisible = False
        ToolbarButton8.MaxDropDownItems = 0
        ToolbarButton8.MaxSubWidth = -1
        ToolbarButton8.MaxWidth = -1
        ToolbarButton8.MenuHorizontalAlignment = -1
        ToolbarButton8.MenuVerticalAlignment = -1
        ToolbarButton8.MinSubWidth = -1
        ToolbarButton8.MinWidth = -1
        ToolbarButton8.Name = ""
        ToolbarButton8.RowsHeightAutoSize = True
        ToolbarButton8.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton8.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton8.ShowColumnCheck = False
        ToolbarButton8.ShowColumnImage = False
        ToolbarButton8.State = False
        ToolbarButton8.SubColumnWidth = CType(resources.GetObject("ToolbarButton8.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton8.SubHeight = 100
        ToolbarButton8.SubItemsAutoSize = False
        ToolbarButton8.SubWidth = 100
        ToolbarButton8.Tag = Nothing
        ToolbarButton8.Text = "Menu"
        ToolbarButton8.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton8.ToolTips = ""
        ToolbarButton8.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton8.Visible = True
        ToolbarButton8.Width = 47
        ToolbarButton9.BackColor = System.Drawing.Color.Empty
        ToolbarButton9.BorderColor = System.Drawing.Color.Silver
        ToolbarButton9.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton9.BorderVisible = False
        ToolbarButton9.DefaultFont = Nothing
        ToolbarButton9.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton9.DefaultRowItemHeight = 0
        ToolbarButton9.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton9.DefaultTitleFont = Nothing
        ToolbarButton9.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton9.DropDown = False
        ToolbarButton9.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton9.DropDownMenuColoumnsCount = 1
        ToolbarButton9.Enabled = True
        ToolbarButton9.EnableSubItemsSelection = True
        ToolbarButton9.Font = Nothing
        ToolbarButton9.ForeColor = System.Drawing.Color.Empty
        ToolbarButton9.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton9.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton9.FullRowSelect = False
        ToolbarButton9.Image = Nothing
        ToolbarButton9.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton9.InternalBorderVisible = False
        ToolbarButton9.MaxDropDownItems = 0
        ToolbarButton9.MaxSubWidth = -1
        ToolbarButton9.MaxWidth = -1
        ToolbarButton9.MenuHorizontalAlignment = -1
        ToolbarButton9.MenuVerticalAlignment = -1
        ToolbarButton9.MinSubWidth = -1
        ToolbarButton9.MinWidth = -1
        ToolbarButton9.Name = ""
        ToolbarButton9.RowsHeightAutoSize = True
        ToolbarButton9.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton9.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton9.ShowColumnCheck = False
        ToolbarButton9.ShowColumnImage = False
        ToolbarButton9.State = False
        ToolbarButton9.SubColumnWidth = CType(resources.GetObject("ToolbarButton9.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton9.SubHeight = 100
        ToolbarButton9.SubItemsAutoSize = False
        ToolbarButton9.SubWidth = 100
        ToolbarButton9.Tag = Nothing
        ToolbarButton9.Text = "Menu"
        ToolbarButton9.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton9.ToolTips = ""
        ToolbarButton9.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton9.Visible = True
        ToolbarButton9.Width = 47
        ToolbarButton10.BackColor = System.Drawing.Color.Empty
        ToolbarButton10.BorderColor = System.Drawing.Color.Silver
        ToolbarButton10.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton10.BorderVisible = False
        ToolbarButton10.DefaultFont = Nothing
        ToolbarButton10.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton10.DefaultRowItemHeight = 0
        ToolbarButton10.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton10.DefaultTitleFont = Nothing
        ToolbarButton10.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton10.DropDown = False
        ToolbarButton10.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton10.DropDownMenuColoumnsCount = 1
        ToolbarButton10.Enabled = True
        ToolbarButton10.EnableSubItemsSelection = True
        ToolbarButton10.Font = Nothing
        ToolbarButton10.ForeColor = System.Drawing.Color.Empty
        ToolbarButton10.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton10.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton10.FullRowSelect = False
        ToolbarButton10.Image = Nothing
        ToolbarButton10.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton10.InternalBorderVisible = False
        ToolbarButton10.MaxDropDownItems = 0
        ToolbarButton10.MaxSubWidth = -1
        ToolbarButton10.MaxWidth = -1
        ToolbarButton10.MenuHorizontalAlignment = -1
        ToolbarButton10.MenuVerticalAlignment = -1
        ToolbarButton10.MinSubWidth = -1
        ToolbarButton10.MinWidth = -1
        ToolbarButton10.Name = ""
        ToolbarButton10.RowsHeightAutoSize = True
        ToolbarButton10.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton10.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton10.ShowColumnCheck = False
        ToolbarButton10.ShowColumnImage = False
        ToolbarButton10.State = False
        ToolbarButton10.SubColumnWidth = CType(resources.GetObject("ToolbarButton10.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton10.SubHeight = 100
        ToolbarButton10.SubItemsAutoSize = False
        ToolbarButton10.SubWidth = 100
        ToolbarButton10.Tag = Nothing
        ToolbarButton10.Text = "Menu"
        ToolbarButton10.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton10.ToolTips = ""
        ToolbarButton10.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton10.Visible = True
        ToolbarButton10.Width = 47
        ToolbarButton11.BackColor = System.Drawing.Color.Empty
        ToolbarButton11.BorderColor = System.Drawing.Color.Silver
        ToolbarButton11.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton11.BorderVisible = False
        ToolbarButton11.DefaultFont = Nothing
        ToolbarButton11.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton11.DefaultRowItemHeight = 0
        ToolbarButton11.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton11.DefaultTitleFont = Nothing
        ToolbarButton11.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton11.DropDown = False
        ToolbarButton11.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton11.DropDownMenuColoumnsCount = 1
        ToolbarButton11.Enabled = True
        ToolbarButton11.EnableSubItemsSelection = True
        ToolbarButton11.Font = Nothing
        ToolbarButton11.ForeColor = System.Drawing.Color.Empty
        ToolbarButton11.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton11.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton11.FullRowSelect = False
        ToolbarButton11.Image = Nothing
        ToolbarButton11.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton11.InternalBorderVisible = False
        ToolbarButton11.MaxDropDownItems = 0
        ToolbarButton11.MaxSubWidth = -1
        ToolbarButton11.MaxWidth = -1
        ToolbarButton11.MenuHorizontalAlignment = -1
        ToolbarButton11.MenuVerticalAlignment = -1
        ToolbarButton11.MinSubWidth = -1
        ToolbarButton11.MinWidth = -1
        ToolbarButton11.Name = ""
        ToolbarButton11.RowsHeightAutoSize = True
        ToolbarButton11.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton11.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton11.ShowColumnCheck = False
        ToolbarButton11.ShowColumnImage = False
        ToolbarButton11.State = False
        ToolbarButton11.SubColumnWidth = CType(resources.GetObject("ToolbarButton11.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton11.SubHeight = 100
        ToolbarButton11.SubItemsAutoSize = False
        ToolbarButton11.SubWidth = 100
        ToolbarButton11.Tag = Nothing
        ToolbarButton11.Text = "Menu"
        ToolbarButton11.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton11.ToolTips = ""
        ToolbarButton11.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton11.Visible = True
        ToolbarButton11.Width = 47
        ToolbarButton12.BackColor = System.Drawing.Color.Empty
        ToolbarButton12.BorderColor = System.Drawing.Color.Silver
        ToolbarButton12.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton12.BorderVisible = False
        ToolbarButton12.DefaultFont = Nothing
        ToolbarButton12.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton12.DefaultRowItemHeight = 0
        ToolbarButton12.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton12.DefaultTitleFont = Nothing
        ToolbarButton12.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton12.DropDown = False
        ToolbarButton12.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton12.DropDownMenuColoumnsCount = 1
        ToolbarButton12.Enabled = True
        ToolbarButton12.EnableSubItemsSelection = True
        ToolbarButton12.Font = Nothing
        ToolbarButton12.ForeColor = System.Drawing.Color.Empty
        ToolbarButton12.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton12.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton12.FullRowSelect = False
        ToolbarButton12.Image = Nothing
        ToolbarButton12.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton12.InternalBorderVisible = False
        ToolbarButton12.MaxDropDownItems = 0
        ToolbarButton12.MaxSubWidth = -1
        ToolbarButton12.MaxWidth = -1
        ToolbarButton12.MenuHorizontalAlignment = -1
        ToolbarButton12.MenuVerticalAlignment = -1
        ToolbarButton12.MinSubWidth = -1
        ToolbarButton12.MinWidth = -1
        ToolbarButton12.Name = ""
        ToolbarButton12.RowsHeightAutoSize = True
        ToolbarButton12.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton12.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton12.ShowColumnCheck = False
        ToolbarButton12.ShowColumnImage = False
        ToolbarButton12.State = False
        ToolbarButton12.SubColumnWidth = CType(resources.GetObject("ToolbarButton12.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton12.SubHeight = 100
        ToolbarButton12.SubItemsAutoSize = False
        ToolbarButton12.SubWidth = 100
        ToolbarButton12.Tag = Nothing
        ToolbarButton12.Text = "Menu"
        ToolbarButton12.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton12.ToolTips = ""
        ToolbarButton12.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton12.Visible = True
        ToolbarButton12.Width = 47
        ToolbarButton13.BackColor = System.Drawing.Color.Empty
        ToolbarButton13.BorderColor = System.Drawing.Color.Silver
        ToolbarButton13.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton13.BorderVisible = False
        ToolbarButton13.DefaultFont = Nothing
        ToolbarButton13.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton13.DefaultRowItemHeight = 0
        ToolbarButton13.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton13.DefaultTitleFont = Nothing
        ToolbarButton13.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton13.DropDown = False
        ToolbarButton13.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton13.DropDownMenuColoumnsCount = 1
        ToolbarButton13.Enabled = True
        ToolbarButton13.EnableSubItemsSelection = True
        ToolbarButton13.Font = Nothing
        ToolbarButton13.ForeColor = System.Drawing.Color.Empty
        ToolbarButton13.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton13.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton13.FullRowSelect = False
        ToolbarButton13.Image = Nothing
        ToolbarButton13.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton13.InternalBorderVisible = False
        ToolbarButton13.MaxDropDownItems = 0
        ToolbarButton13.MaxSubWidth = -1
        ToolbarButton13.MaxWidth = -1
        ToolbarButton13.MenuHorizontalAlignment = -1
        ToolbarButton13.MenuVerticalAlignment = -1
        ToolbarButton13.MinSubWidth = -1
        ToolbarButton13.MinWidth = -1
        ToolbarButton13.Name = ""
        ToolbarButton13.RowsHeightAutoSize = True
        ToolbarButton13.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton13.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton13.ShowColumnCheck = False
        ToolbarButton13.ShowColumnImage = False
        ToolbarButton13.State = False
        ToolbarButton13.SubColumnWidth = CType(resources.GetObject("ToolbarButton13.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton13.SubHeight = 100
        ToolbarButton13.SubItemsAutoSize = False
        ToolbarButton13.SubWidth = 100
        ToolbarButton13.Tag = Nothing
        ToolbarButton13.Text = "Menu"
        ToolbarButton13.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton13.ToolTips = ""
        ToolbarButton13.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton13.Visible = True
        ToolbarButton13.Width = 47
        ToolbarButton14.BackColor = System.Drawing.Color.Empty
        ToolbarButton14.BorderColor = System.Drawing.Color.Silver
        ToolbarButton14.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton14.BorderVisible = False
        ToolbarButton14.DefaultFont = Nothing
        ToolbarButton14.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton14.DefaultRowItemHeight = 0
        ToolbarButton14.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton14.DefaultTitleFont = Nothing
        ToolbarButton14.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton14.DropDown = False
        ToolbarButton14.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton14.DropDownMenuColoumnsCount = 1
        ToolbarButton14.Enabled = True
        ToolbarButton14.EnableSubItemsSelection = True
        ToolbarButton14.Font = Nothing
        ToolbarButton14.ForeColor = System.Drawing.Color.Empty
        ToolbarButton14.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton14.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton14.FullRowSelect = False
        ToolbarButton14.Image = Nothing
        ToolbarButton14.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton14.InternalBorderVisible = False
        ToolbarButton14.MaxDropDownItems = 0
        ToolbarButton14.MaxSubWidth = -1
        ToolbarButton14.MaxWidth = -1
        ToolbarButton14.MenuHorizontalAlignment = -1
        ToolbarButton14.MenuVerticalAlignment = -1
        ToolbarButton14.MinSubWidth = -1
        ToolbarButton14.MinWidth = -1
        ToolbarButton14.Name = ""
        ToolbarButton14.RowsHeightAutoSize = True
        ToolbarButton14.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton14.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton14.ShowColumnCheck = False
        ToolbarButton14.ShowColumnImage = False
        ToolbarButton14.State = False
        ToolbarButton14.SubColumnWidth = CType(resources.GetObject("ToolbarButton14.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton14.SubHeight = 100
        ToolbarButton14.SubItemsAutoSize = False
        ToolbarButton14.SubWidth = 100
        ToolbarButton14.Tag = Nothing
        ToolbarButton14.Text = "Menu"
        ToolbarButton14.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton14.ToolTips = ""
        ToolbarButton14.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton14.Visible = True
        ToolbarButton14.Width = 47
        ToolbarButton15.BackColor = System.Drawing.Color.Empty
        ToolbarButton15.BorderColor = System.Drawing.Color.Silver
        ToolbarButton15.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton15.BorderVisible = False
        ToolbarButton15.DefaultFont = Nothing
        ToolbarButton15.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton15.DefaultRowItemHeight = 0
        ToolbarButton15.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton15.DefaultTitleFont = Nothing
        ToolbarButton15.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton15.DropDown = False
        ToolbarButton15.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton15.DropDownMenuColoumnsCount = 1
        ToolbarButton15.Enabled = True
        ToolbarButton15.EnableSubItemsSelection = True
        ToolbarButton15.Font = Nothing
        ToolbarButton15.ForeColor = System.Drawing.Color.Empty
        ToolbarButton15.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton15.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton15.FullRowSelect = False
        ToolbarButton15.Image = Nothing
        ToolbarButton15.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton15.InternalBorderVisible = False
        ToolbarButton15.MaxDropDownItems = 0
        ToolbarButton15.MaxSubWidth = -1
        ToolbarButton15.MaxWidth = -1
        ToolbarButton15.MenuHorizontalAlignment = -1
        ToolbarButton15.MenuVerticalAlignment = -1
        ToolbarButton15.MinSubWidth = -1
        ToolbarButton15.MinWidth = -1
        ToolbarButton15.Name = ""
        ToolbarButton15.RowsHeightAutoSize = True
        ToolbarButton15.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton15.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton15.ShowColumnCheck = False
        ToolbarButton15.ShowColumnImage = False
        ToolbarButton15.State = False
        ToolbarButton15.SubColumnWidth = CType(resources.GetObject("ToolbarButton15.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton15.SubHeight = 100
        ToolbarButton15.SubItemsAutoSize = False
        ToolbarButton15.SubWidth = 100
        ToolbarButton15.Tag = Nothing
        ToolbarButton15.Text = "Menu"
        ToolbarButton15.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton15.ToolTips = ""
        ToolbarButton15.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton15.Visible = True
        ToolbarButton15.Width = 47
        ToolbarButton16.BackColor = System.Drawing.Color.Empty
        ToolbarButton16.BorderColor = System.Drawing.Color.Silver
        ToolbarButton16.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton16.BorderVisible = False
        ToolbarButton16.DefaultFont = Nothing
        ToolbarButton16.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton16.DefaultRowItemHeight = 0
        ToolbarButton16.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton16.DefaultTitleFont = Nothing
        ToolbarButton16.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton16.DropDown = False
        ToolbarButton16.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton16.DropDownMenuColoumnsCount = 1
        ToolbarButton16.Enabled = True
        ToolbarButton16.EnableSubItemsSelection = True
        ToolbarButton16.Font = Nothing
        ToolbarButton16.ForeColor = System.Drawing.Color.Empty
        ToolbarButton16.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton16.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton16.FullRowSelect = False
        ToolbarButton16.Image = Nothing
        ToolbarButton16.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton16.InternalBorderVisible = False
        ToolbarButton16.MaxDropDownItems = 0
        ToolbarButton16.MaxSubWidth = -1
        ToolbarButton16.MaxWidth = -1
        ToolbarButton16.MenuHorizontalAlignment = -1
        ToolbarButton16.MenuVerticalAlignment = -1
        ToolbarButton16.MinSubWidth = -1
        ToolbarButton16.MinWidth = -1
        ToolbarButton16.Name = ""
        ToolbarButton16.RowsHeightAutoSize = True
        ToolbarButton16.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton16.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton16.ShowColumnCheck = False
        ToolbarButton16.ShowColumnImage = False
        ToolbarButton16.State = False
        ToolbarButton16.SubColumnWidth = CType(resources.GetObject("ToolbarButton16.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton16.SubHeight = 100
        ToolbarButton16.SubItemsAutoSize = False
        ToolbarButton16.SubWidth = 100
        ToolbarButton16.Tag = Nothing
        ToolbarButton16.Text = "Menu"
        ToolbarButton16.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton16.ToolTips = ""
        ToolbarButton16.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton16.Visible = True
        ToolbarButton16.Width = 47
        ToolbarButton17.BackColor = System.Drawing.Color.Empty
        ToolbarButton17.BorderColor = System.Drawing.Color.Silver
        ToolbarButton17.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton17.BorderVisible = False
        ToolbarButton17.DefaultFont = Nothing
        ToolbarButton17.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton17.DefaultRowItemHeight = 0
        ToolbarButton17.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton17.DefaultTitleFont = Nothing
        ToolbarButton17.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton17.DropDown = False
        ToolbarButton17.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton17.DropDownMenuColoumnsCount = 1
        ToolbarButton17.Enabled = True
        ToolbarButton17.EnableSubItemsSelection = True
        ToolbarButton17.Font = Nothing
        ToolbarButton17.ForeColor = System.Drawing.Color.Empty
        ToolbarButton17.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton17.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton17.FullRowSelect = False
        ToolbarButton17.Image = Nothing
        ToolbarButton17.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton17.InternalBorderVisible = False
        ToolbarButton17.MaxDropDownItems = 0
        ToolbarButton17.MaxSubWidth = -1
        ToolbarButton17.MaxWidth = -1
        ToolbarButton17.MenuHorizontalAlignment = -1
        ToolbarButton17.MenuVerticalAlignment = -1
        ToolbarButton17.MinSubWidth = -1
        ToolbarButton17.MinWidth = -1
        ToolbarButton17.Name = ""
        ToolbarButton17.RowsHeightAutoSize = True
        ToolbarButton17.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton17.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton17.ShowColumnCheck = False
        ToolbarButton17.ShowColumnImage = False
        ToolbarButton17.State = False
        ToolbarButton17.SubColumnWidth = CType(resources.GetObject("ToolbarButton17.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton17.SubHeight = 100
        ToolbarButton17.SubItemsAutoSize = False
        ToolbarButton17.SubWidth = 100
        ToolbarButton17.Tag = Nothing
        ToolbarButton17.Text = "Menu"
        ToolbarButton17.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton17.ToolTips = ""
        ToolbarButton17.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton17.Visible = True
        ToolbarButton17.Width = 47
        ToolbarButton18.BackColor = System.Drawing.Color.Empty
        ToolbarButton18.BorderColor = System.Drawing.Color.Silver
        ToolbarButton18.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton18.BorderVisible = False
        ToolbarButton18.DefaultFont = Nothing
        ToolbarButton18.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton18.DefaultRowItemHeight = 0
        ToolbarButton18.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton18.DefaultTitleFont = Nothing
        ToolbarButton18.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton18.DropDown = False
        ToolbarButton18.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton18.DropDownMenuColoumnsCount = 1
        ToolbarButton18.Enabled = True
        ToolbarButton18.EnableSubItemsSelection = True
        ToolbarButton18.Font = Nothing
        ToolbarButton18.ForeColor = System.Drawing.Color.Empty
        ToolbarButton18.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton18.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton18.FullRowSelect = False
        ToolbarButton18.Image = Nothing
        ToolbarButton18.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton18.InternalBorderVisible = False
        ToolbarButton18.MaxDropDownItems = 0
        ToolbarButton18.MaxSubWidth = -1
        ToolbarButton18.MaxWidth = -1
        ToolbarButton18.MenuHorizontalAlignment = -1
        ToolbarButton18.MenuVerticalAlignment = -1
        ToolbarButton18.MinSubWidth = -1
        ToolbarButton18.MinWidth = -1
        ToolbarButton18.Name = ""
        ToolbarButton18.RowsHeightAutoSize = True
        ToolbarButton18.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton18.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton18.ShowColumnCheck = False
        ToolbarButton18.ShowColumnImage = False
        ToolbarButton18.State = False
        ToolbarButton18.SubColumnWidth = CType(resources.GetObject("ToolbarButton18.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton18.SubHeight = 100
        ToolbarButton18.SubItemsAutoSize = False
        ToolbarButton18.SubWidth = 100
        ToolbarButton18.Tag = Nothing
        ToolbarButton18.Text = "Menu"
        ToolbarButton18.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton18.ToolTips = ""
        ToolbarButton18.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton18.Visible = True
        ToolbarButton18.Width = 47
        ToolbarButton19.BackColor = System.Drawing.Color.Empty
        ToolbarButton19.BorderColor = System.Drawing.Color.Silver
        ToolbarButton19.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton19.BorderVisible = False
        ToolbarButton19.DefaultFont = Nothing
        ToolbarButton19.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton19.DefaultRowItemHeight = 0
        ToolbarButton19.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton19.DefaultTitleFont = Nothing
        ToolbarButton19.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton19.DropDown = False
        ToolbarButton19.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton19.DropDownMenuColoumnsCount = 1
        ToolbarButton19.Enabled = True
        ToolbarButton19.EnableSubItemsSelection = True
        ToolbarButton19.Font = Nothing
        ToolbarButton19.ForeColor = System.Drawing.Color.Empty
        ToolbarButton19.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton19.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton19.FullRowSelect = False
        ToolbarButton19.Image = Nothing
        ToolbarButton19.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton19.InternalBorderVisible = False
        ToolbarButton19.MaxDropDownItems = 0
        ToolbarButton19.MaxSubWidth = -1
        ToolbarButton19.MaxWidth = -1
        ToolbarButton19.MenuHorizontalAlignment = -1
        ToolbarButton19.MenuVerticalAlignment = -1
        ToolbarButton19.MinSubWidth = -1
        ToolbarButton19.MinWidth = -1
        ToolbarButton19.Name = ""
        ToolbarButton19.RowsHeightAutoSize = True
        ToolbarButton19.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton19.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton19.ShowColumnCheck = False
        ToolbarButton19.ShowColumnImage = False
        ToolbarButton19.State = False
        ToolbarButton19.SubColumnWidth = CType(resources.GetObject("ToolbarButton19.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton19.SubHeight = 100
        ToolbarButton19.SubItemsAutoSize = False
        ToolbarButton19.SubWidth = 100
        ToolbarButton19.Tag = Nothing
        ToolbarButton19.Text = "Menu"
        ToolbarButton19.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton19.ToolTips = ""
        ToolbarButton19.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton19.Visible = True
        ToolbarButton19.Width = 47
        ToolbarButton20.BackColor = System.Drawing.Color.Empty
        ToolbarButton20.BorderColor = System.Drawing.Color.Silver
        ToolbarButton20.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton20.BorderVisible = False
        ToolbarButton20.DefaultFont = Nothing
        ToolbarButton20.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton20.DefaultRowItemHeight = 0
        ToolbarButton20.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton20.DefaultTitleFont = Nothing
        ToolbarButton20.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton20.DropDown = False
        ToolbarButton20.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton20.DropDownMenuColoumnsCount = 1
        ToolbarButton20.Enabled = True
        ToolbarButton20.EnableSubItemsSelection = True
        ToolbarButton20.Font = Nothing
        ToolbarButton20.ForeColor = System.Drawing.Color.Empty
        ToolbarButton20.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton20.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton20.FullRowSelect = False
        ToolbarButton20.Image = Nothing
        ToolbarButton20.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton20.InternalBorderVisible = False
        ToolbarButton20.MaxDropDownItems = 0
        ToolbarButton20.MaxSubWidth = -1
        ToolbarButton20.MaxWidth = -1
        ToolbarButton20.MenuHorizontalAlignment = -1
        ToolbarButton20.MenuVerticalAlignment = -1
        ToolbarButton20.MinSubWidth = -1
        ToolbarButton20.MinWidth = -1
        ToolbarButton20.Name = ""
        ToolbarButton20.RowsHeightAutoSize = True
        ToolbarButton20.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton20.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton20.ShowColumnCheck = False
        ToolbarButton20.ShowColumnImage = False
        ToolbarButton20.State = False
        ToolbarButton20.SubColumnWidth = CType(resources.GetObject("ToolbarButton20.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton20.SubHeight = 100
        ToolbarButton20.SubItemsAutoSize = False
        ToolbarButton20.SubWidth = 100
        ToolbarButton20.Tag = Nothing
        ToolbarButton20.Text = "Menu"
        ToolbarButton20.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton20.ToolTips = ""
        ToolbarButton20.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton20.Visible = True
        ToolbarButton20.Width = 47
        ToolbarButton21.BackColor = System.Drawing.Color.Empty
        ToolbarButton21.BorderColor = System.Drawing.Color.Silver
        ToolbarButton21.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton21.BorderVisible = False
        ToolbarButton21.DefaultFont = Nothing
        ToolbarButton21.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton21.DefaultRowItemHeight = 0
        ToolbarButton21.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton21.DefaultTitleFont = Nothing
        ToolbarButton21.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton21.DropDown = False
        ToolbarButton21.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton21.DropDownMenuColoumnsCount = 1
        ToolbarButton21.Enabled = True
        ToolbarButton21.EnableSubItemsSelection = True
        ToolbarButton21.Font = Nothing
        ToolbarButton21.ForeColor = System.Drawing.Color.Empty
        ToolbarButton21.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton21.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton21.FullRowSelect = False
        ToolbarButton21.Image = Nothing
        ToolbarButton21.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton21.InternalBorderVisible = False
        ToolbarButton21.MaxDropDownItems = 0
        ToolbarButton21.MaxSubWidth = -1
        ToolbarButton21.MaxWidth = -1
        ToolbarButton21.MenuHorizontalAlignment = -1
        ToolbarButton21.MenuVerticalAlignment = -1
        ToolbarButton21.MinSubWidth = -1
        ToolbarButton21.MinWidth = -1
        ToolbarButton21.Name = ""
        ToolbarButton21.RowsHeightAutoSize = True
        ToolbarButton21.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton21.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton21.ShowColumnCheck = False
        ToolbarButton21.ShowColumnImage = False
        ToolbarButton21.State = False
        ToolbarButton21.SubColumnWidth = CType(resources.GetObject("ToolbarButton21.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton21.SubHeight = 100
        ToolbarButton21.SubItemsAutoSize = False
        ToolbarButton21.SubWidth = 100
        ToolbarButton21.Tag = Nothing
        ToolbarButton21.Text = "Menu"
        ToolbarButton21.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton21.ToolTips = ""
        ToolbarButton21.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton21.Visible = True
        ToolbarButton21.Width = 47
        ToolbarButton22.BackColor = System.Drawing.Color.Empty
        ToolbarButton22.BorderColor = System.Drawing.Color.Silver
        ToolbarButton22.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton22.BorderVisible = False
        ToolbarButton22.DefaultFont = Nothing
        ToolbarButton22.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton22.DefaultRowItemHeight = 0
        ToolbarButton22.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton22.DefaultTitleFont = Nothing
        ToolbarButton22.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton22.DropDown = False
        ToolbarButton22.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton22.DropDownMenuColoumnsCount = 1
        ToolbarButton22.Enabled = True
        ToolbarButton22.EnableSubItemsSelection = True
        ToolbarButton22.Font = Nothing
        ToolbarButton22.ForeColor = System.Drawing.Color.Empty
        ToolbarButton22.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton22.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton22.FullRowSelect = False
        ToolbarButton22.Image = Nothing
        ToolbarButton22.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton22.InternalBorderVisible = False
        ToolbarButton22.MaxDropDownItems = 0
        ToolbarButton22.MaxSubWidth = -1
        ToolbarButton22.MaxWidth = -1
        ToolbarButton22.MenuHorizontalAlignment = -1
        ToolbarButton22.MenuVerticalAlignment = -1
        ToolbarButton22.MinSubWidth = -1
        ToolbarButton22.MinWidth = -1
        ToolbarButton22.Name = ""
        ToolbarButton22.RowsHeightAutoSize = True
        ToolbarButton22.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton22.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton22.ShowColumnCheck = False
        ToolbarButton22.ShowColumnImage = False
        ToolbarButton22.State = False
        ToolbarButton22.SubColumnWidth = CType(resources.GetObject("ToolbarButton22.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton22.SubHeight = 100
        ToolbarButton22.SubItemsAutoSize = False
        ToolbarButton22.SubWidth = 100
        ToolbarButton22.Tag = Nothing
        ToolbarButton22.Text = "Menu"
        ToolbarButton22.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton22.ToolTips = ""
        ToolbarButton22.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton22.Visible = True
        ToolbarButton22.Width = 47
        ToolbarButton23.BackColor = System.Drawing.Color.Empty
        ToolbarButton23.BorderColor = System.Drawing.Color.Silver
        ToolbarButton23.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton23.BorderVisible = False
        ToolbarButton23.DefaultFont = Nothing
        ToolbarButton23.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton23.DefaultRowItemHeight = 0
        ToolbarButton23.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton23.DefaultTitleFont = Nothing
        ToolbarButton23.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton23.DropDown = False
        ToolbarButton23.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton23.DropDownMenuColoumnsCount = 1
        ToolbarButton23.Enabled = True
        ToolbarButton23.EnableSubItemsSelection = True
        ToolbarButton23.Font = Nothing
        ToolbarButton23.ForeColor = System.Drawing.Color.Empty
        ToolbarButton23.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton23.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton23.FullRowSelect = False
        ToolbarButton23.Image = Nothing
        ToolbarButton23.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton23.InternalBorderVisible = False
        ToolbarButton23.MaxDropDownItems = 0
        ToolbarButton23.MaxSubWidth = -1
        ToolbarButton23.MaxWidth = -1
        ToolbarButton23.MenuHorizontalAlignment = -1
        ToolbarButton23.MenuVerticalAlignment = -1
        ToolbarButton23.MinSubWidth = -1
        ToolbarButton23.MinWidth = -1
        ToolbarButton23.Name = ""
        ToolbarButton23.RowsHeightAutoSize = True
        ToolbarButton23.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton23.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton23.ShowColumnCheck = False
        ToolbarButton23.ShowColumnImage = False
        ToolbarButton23.State = False
        ToolbarButton23.SubColumnWidth = CType(resources.GetObject("ToolbarButton23.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton23.SubHeight = 100
        ToolbarButton23.SubItemsAutoSize = False
        ToolbarButton23.SubWidth = 100
        ToolbarButton23.Tag = Nothing
        ToolbarButton23.Text = "Menu"
        ToolbarButton23.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton23.ToolTips = ""
        ToolbarButton23.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton23.Visible = True
        ToolbarButton23.Width = 47
        ToolbarButton24.BackColor = System.Drawing.Color.Empty
        ToolbarButton24.BorderColor = System.Drawing.Color.Silver
        ToolbarButton24.BorderColorDropDown = System.Drawing.Color.Silver
        ToolbarButton24.BorderVisible = False
        ToolbarButton24.DefaultFont = Nothing
        ToolbarButton24.DefaultForeColor = System.Drawing.Color.Empty
        ToolbarButton24.DefaultRowItemHeight = 0
        ToolbarButton24.DefaultSubItemsContentAlignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        ToolbarButton24.DefaultTitleFont = Nothing
        ToolbarButton24.DefaultTitleForeColor = System.Drawing.Color.Empty
        ToolbarButton24.DropDown = False
        ToolbarButton24.DropDownArrowAlignment = System.Windows.Forms.HorizontalAlignment.Right
        ToolbarButton24.DropDownMenuColoumnsCount = 1
        ToolbarButton24.Enabled = True
        ToolbarButton24.EnableSubItemsSelection = True
        ToolbarButton24.Font = Nothing
        ToolbarButton24.ForeColor = System.Drawing.Color.Empty
        ToolbarButton24.ForeColorDropDown = System.Drawing.Color.Empty
        ToolbarButton24.ForeColorSelect = System.Drawing.Color.Empty
        ToolbarButton24.FullRowSelect = False
        ToolbarButton24.Image = Nothing
        ToolbarButton24.InternalBorderColor = System.Drawing.Color.Empty
        ToolbarButton24.InternalBorderVisible = False
        ToolbarButton24.MaxDropDownItems = 0
        ToolbarButton24.MaxSubWidth = -1
        ToolbarButton24.MaxWidth = -1
        ToolbarButton24.MenuHorizontalAlignment = -1
        ToolbarButton24.MenuVerticalAlignment = -1
        ToolbarButton24.MinSubWidth = -1
        ToolbarButton24.MinWidth = -1
        ToolbarButton24.Name = ""
        ToolbarButton24.RowsHeightAutoSize = True
        ToolbarButton24.SelectionColor = System.Drawing.Color.Empty
        ToolbarButton24.SelectionColorDropDown = System.Drawing.Color.Empty
        ToolbarButton24.ShowColumnCheck = False
        ToolbarButton24.ShowColumnImage = False
        ToolbarButton24.State = False
        ToolbarButton24.SubColumnWidth = CType(resources.GetObject("ToolbarButton24.SubColumnWidth"), System.Collections.Generic.List(Of Integer))
        ToolbarButton24.SubHeight = 100
        ToolbarButton24.SubItemsAutoSize = False
        ToolbarButton24.SubWidth = 100
        ToolbarButton24.Tag = Nothing
        ToolbarButton24.Text = "Menu"
        ToolbarButton24.TextAlign = System.Windows.Forms.HorizontalAlignment.Left
        ToolbarButton24.ToolTips = ""
        ToolbarButton24.Type = iControl.ToolbarButton.iType.ButtonDropDown
        ToolbarButton24.Visible = True
        ToolbarButton24.Width = 47
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton3)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton4)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton5)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton6)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton7)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton8)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton9)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton10)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton11)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton12)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton13)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton14)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton15)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton16)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton17)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton18)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton19)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton20)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton21)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton22)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton23)
        Me.IForm1.WindowMenu.Button.Add(ToolbarButton24)
        Me.IForm1.WindowMenu.Dull = False
        Me.IForm1.WindowMenu.EnabledSelection = False
        Me.IForm1.WindowMenu.FlatStyle = False
        Me.IForm1.WindowMenu.Font = New System.Drawing.Font("Arial", 11.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel, CType(0, Byte))
        Me.IForm1.WindowMenu.ForeColor = System.Drawing.Color.DimGray
        Me.IForm1.WindowMenu.ForeColorDropDown = System.Drawing.Color.DimGray
        Me.IForm1.WindowMenu.ForeColorSelect = System.Drawing.Color.DimGray
        Me.IForm1.WindowMenu.Location = New System.Drawing.Point(48, 15)
        Me.IForm1.WindowMenu.MaxDropDownItems = 8
        Me.IForm1.WindowMenu.MenuHorizontalAlignment = 0
        Me.IForm1.WindowMenu.MenuVerticalAlignment = 0
        Me.IForm1.WindowMenu.MultiSelection = False
        Me.IForm1.WindowMenu.Name = "tlbmenu"
        Me.IForm1.WindowMenu.ReadOnly = False
        Me.IForm1.WindowMenu.SelectionColor = System.Drawing.Color.White
        Me.IForm1.WindowMenu.SelectionColorDropDown = System.Drawing.Color.White
        Me.IForm1.WindowMenu.SeparatorColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.IForm1.WindowMenu.Size = New System.Drawing.Size(1037, 24)
        Me.IForm1.WindowMenu.SubItemsMultiSelection = False
        Me.IForm1.WindowMenu.SuspundeLayout = False
        Me.IForm1.WindowMenu.TabIndex = 160
        Me.IForm1.WindowMenu.TextAntiAlis = False
        Me.IForm1.WindowMenu.TextGlowEffetct = False
        Me.IForm1.WindowMenu.TextShadows = False
        Me.IForm1.WindowMenu.ToolbarBorderColor = System.Drawing.Color.DimGray
        Me.IForm1.WindowMenu.ToolbarBorderVisible = False
        Me.IForm1.WindowMenu.ToolbarPadding = 1
        Me.IForm1.WindowMenu.ToolTipDown = True
        Me.IForm1.WindowMenu.Visible = False
        Me.IForm1.WindowMenuLeft = 9
        Me.IForm1.WindowMenuMinWidth = -1
        Me.IForm1.WindowMenuPadding = 9
        Me.IForm1.WindowsClipping = True
        Me.IForm1.WindowsTitle = "iFanta"
        '
        'lbstatus
        '
        Me.lbstatus.Anchor = CType(((System.Windows.Forms.AnchorStyles.Bottom Or System.Windows.Forms.AnchorStyles.Left) _
            Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.lbstatus.AutoSize = True
        Me.lbstatus.Font = New System.Drawing.Font("Arial", 11.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel, CType(0, Byte))
        Me.lbstatus.Location = New System.Drawing.Point(12, 249)
        Me.lbstatus.Name = "lbstatus"
        Me.lbstatus.Size = New System.Drawing.Size(42, 15)
        Me.lbstatus.TabIndex = 266
        Me.lbstatus.Text = "Ready"
        '
        'chkopt
        '
        Me.chkopt.Alignment = System.Windows.Forms.HorizontalAlignment.Left
        Me.chkopt.Background = Nothing
        Me.chkopt.BackgroundImage = CType(resources.GetObject("chkopt.BackgroundImage"), System.Drawing.Image)
        Me.chkopt.BorderColor = System.Drawing.Color.DimGray
        Me.chkopt.BorderSize = 0
        Me.chkopt.BorderVisible = False
        Me.chkopt.Dull = False
        Me.chkopt.EnalbedStyleValueMode = False
        Me.chkopt.Font = New System.Drawing.Font("Arial", 11.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel, CType(0, Byte))
        Me.chkopt.ForeColor = System.Drawing.Color.FromArgb(CType(CType(80, Byte), Integer), CType(CType(80, Byte), Integer), CType(CType(80, Byte), Integer))
        Me.chkopt.LineAlignment = System.Drawing.StringAlignment.Center
        Me.chkopt.Location = New System.Drawing.Point(23, 135)
        Me.chkopt.Name = "chkopt"
        Me.chkopt.ReadOnly = False
        Me.chkopt.Size = New System.Drawing.Size(331, 20)
        Me.chkopt.SuspundeLayout = False
        Me.chkopt.TabIndex = 282
        Me.chkopt.Text = "Opzioni avanzate"
        Me.chkopt.TextAntiAlis = False
        Me.chkopt.TextGlowEffetct = False
        Me.chkopt.TextShadows = False
        Me.chkopt.Value = True
        Me.chkopt.WordWrap = False
        '
        'frmupdateserver
        '
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None
        Me.BackColor = System.Drawing.Color.White
        Me.ClientSize = New System.Drawing.Size(441, 351)
        Me.Controls.Add(Me.chkopt)
        Me.Controls.Add(Me.tlbaction)
        Me.Controls.Add(Me.lbby)
        Me.Controls.Add(Me.lbtorneo1)
        Me.Controls.Add(Me.lbtorneo2)
        Me.Controls.Add(Me.lbmain)
        Me.Controls.Add(Me.pic1)
        Me.Controls.Add(Me.chkimg)
        Me.Controls.Add(Me.chkdata)
        Me.Controls.Add(Me.chkconf)
        Me.Controls.Add(Me.prb1)
        Me.Controls.Add(Me.ILine1)
        Me.Controls.Add(Me.IForm1)
        Me.Controls.Add(Me.lbstatus)
        Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None
        Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
        Me.Name = "frmupdateserver"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "Aggiornamento dati server"
        CType(Me.pic1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
    Friend WithEvents tlbaction As iControl.iToolBar
    Friend WithEvents lbby As iControl.iLabel
    Friend WithEvents lbtorneo1 As iControl.iLabel
    Friend WithEvents lbtorneo2 As iControl.iLabel
    Friend WithEvents lbmain As iControl.iLabel
    Friend WithEvents pic1 As System.Windows.Forms.PictureBox
    Friend WithEvents chkimg As iControl.iCheckBox
    Friend WithEvents chkdata As iControl.iCheckBox
    Friend WithEvents chkconf As iControl.iCheckBox
    Friend WithEvents prb1 As iControl.iProgressBar
    Friend WithEvents ILine1 As iControl.iLine
    Friend WithEvents IForm1 As iControl.iForm
    Friend WithEvents lbstatus As System.Windows.Forms.Label
    Friend WithEvents chkopt As iControl.iCheckBox
End Class
